Performance pitfall in W3C propagation
signalfx/signalfx-dotnet-tracing pull request #115
Opened 2021-06-17 10:21 UTC by dszmigielski

*What*
Removing unnecessary logging and changing level from WARNING to DEBUG to improve performance.

*Why*
When enabling W3C propagation server side will hit performance pitfall due to excessive logging if the header is missing.

2021-06-17 16:33 UTC, pjanotti requested changes
We can still avoid a few allocations on the typical case (no incoming headers). The API suggestion for TraceId is not required but logging seems better if out of it: we can give better contextual information about the type of header.

2021-06-17 16:33 UTC, pjanotti commented on src/Datadog.Trace/Propagation/W3CSpanContextPropagator.cs
>              var traceParentCollection = getter(carrier, W3CHeaderNames.TraceParent).ToList();
This should follow the same pattern at https://github.com/signalfx/signalfx-dotnet-tracing/blob/bff4458480463a75d870b41504eec6f08294ed47/src/Datadog.Trace/Propagation/PropagationHelpers.cs#L10-L35

See PR https://github.com/signalfx/signalfx-dotnet-tracing/pull/106

2021-06-17 16:33 UTC, pjanotti commented on src/Datadog.Trace/Propagation/W3CSpanContextPropagator.cs
>              var traceParentCollection = getter(carrier, W3CHeaderNames.TraceParent).ToList();
This avoids allocating for a very common case: no incoming headers.

2021-06-17 16:33 UTC, pjanotti commented on src/Datadog.Trace/TraceId.cs
> +                Log.Debug($"Could not parse TraceId from string {id}. {ex.Message}");
Adding this here will double the logging for B3 propagation in case of error. It seems that we need two APIs: `TryParse` and `Parse` instead of `CreateFromString` following the traditional pattern for .NET.  As it is it logs error if the string had length 16 or 32 and failed to parse but not if it had an invalid length.

In general this type of logging should be on the higher level not on a type that is a "primitive" type.

2021-06-17 17:00 UTC, dszmigielski commented on src/Datadog.Trace/TraceId.cs
> +                Log.Debug($"Could not parse TraceId from string {id}. {ex.Message}");
I will change that tomorrow, as changing the API requires a bit more caution so I don't break the rest of the code.

2021-06-17 17:00 UTC, dszmigielski commented on src/Datadog.Trace/Propagation/W3CSpanContextPropagator.cs
>              var traceParentCollection = getter(carrier, W3CHeaderNames.TraceParent).ToList();
Done

2021-06-17 17:52 UTC, pjanotti commented on src/Datadog.Trace/Propagation/W3CSpanContextPropagator.cs
> +            var traceParentHeader = enumerableHeaderValues.First();
This makes me wonder if we can assume single header value for B3 too... we should look into that, and perhaps make it configurable but this is out of scope for this PR.

2021-06-18 12:02 UTC, RassK commented on src/Datadog.Trace/Propagation/W3CSpanContextPropagator.cs
> +            if (!TraceId.TryParse(traceIdString, out var traceId))
just a nit: I typically do not declare the out var inline when it's not used in the declared scope. Although technically it's not scope leaking, for readability imo it's for sure scope leaking. What others think about that feature? @pjanotti @pellared

2021-06-18 12:19 UTC, pellared commented on src/Datadog.Trace/Propagation/W3CSpanContextPropagator.cs
> +            if (!TraceId.TryParse(traceIdString, out var traceId))
personally, I do not like `out var` at all 😄

2021-06-18 12:27 UTC, dszmigielski commented on src/Datadog.Trace/Propagation/W3CSpanContextPropagator.cs
> +            if (!TraceId.TryParse(traceIdString, out var traceId))
I like it tbh 😄 I can see why you can find it unreadable though.

2021-06-21 16:13 UTC, pjanotti commented on src/Datadog.Trace/Propagation/W3CSpanContextPropagator.cs
> +            if (!TraceId.TryParse(traceIdString, out var traceId))
I don't have anything against `out var` sometimes it can be benefit of an explicit type but in the case of a `TryParse` it is clear because of the type must be before the method. Scope usage is kind of related I don't have strong opinion in this case so if people prefer to declare outside it is fine for me.

2021-06-21 16:16 UTC, pjanotti approved these changes
LGTM

2021-06-21 16:37 UTC, pellared commented on src/Datadog.Trace/Propagation/W3CSpanContextPropagator.cs
> +            if (!TraceId.TryParse(traceIdString, out var traceId))
I do not have a strong opinion as well

2021-06-21 16:39 UTC, pellared commented on src/Datadog.Trace/TraceId.cs
> +                    throw new FormatException("The passed string must have 16 or 32 signs");
I think "character" is a better word than "sign". In Polish it is the same word but I think that in English sign is a little different

2021-06-22 21:12 UTC, pellared commented on src/Datadog.Trace/TraceId.cs
> +        public static TraceId Parse(string id)
Cannot we return `TraceId.Zero` instead of throwing the exception?
I think this method is not used anywhere except tests and `TryParse` and most often if `TryParse` returns `false` than there is a fallback to set `TraceId.Zerp` instead (which is not needed BTW).

We can sync if I am not clear

2021-06-23 04:13 UTC, dszmigielski commented on src/Datadog.Trace/TraceId.cs
> +        public static TraceId Parse(string id)
Logging was an issue. I didn't know if someone passed `TraceId` equal to `0` or something that failed to parse - we log these differently. The fallback was just a safeguard for me if I miss some usages (so the behaviour stays the same).

2021-06-23 06:32 UTC, pellared approved these changes

2021-06-23 15:08 UTC, pjanotti approved these changes

2021-06-23 15:22 UTC, merged