Documentation restructure
signalfx/signalfx-dotnet-tracing pull request #251
Opened 2021-12-13 10:30 UTC by pellared

## Why

Restructure the docs to make it similar to https://github.com/signalfx/splunk-otel-java and https://github.com/signalfx/splunk-otel-python

## What

See commit messages.

2021-12-13 11:23 UTC, pellared commented on docs/CONTRIBUTING.md
> +1. You are working against the latest source on the `main` branch.
I can change it to `next-ver` but I assume for now and we will change it when we update the default branch.
@RassK are you OK with it?

2021-12-13 11:23 UTC, pellared commented on docs/DEVELOPING.md
> +- [Visual Studio 2019 (16.8)](https://visualstudio.microsoft.com/downloads/) or newer
```suggestion
- [Visual Studio 2022 (17.0)](https://visualstudio.microsoft.com/downloads/) or newer
```

2021-12-13 11:26 UTC, pellared commented on docs/README.md
> +- .NET (Core) 3.1 and higher on Windows and Linux
I was thinking about it but MS started to link .NET Core 3.1 in .NET pages. example:

how about this:

```suggestion
- [.NET (Core) 3.1 and higher](https://dotnet.microsoft.com/en-us/download/dotnet) on Windows and Linux
```

and adding https://dotnet.microsoft.com/en-us/download/dotnet-framework for .NET Fx?

2021-12-13 11:27 UTC, pellared commented on docs/DEVELOPING.md
> +.\build.cmd --help
I will address it in next PR

2021-12-13 11:33 UTC, Kielek commented on docs/DEVELOPING.md
> +- [.NET 5.0 SDK](https://dotnet.microsoft.com/download/dotnet/5.0)
.NET 6.0

2021-12-13 11:37 UTC, pellared commented on docs/DEVELOPING.md
> +- [.NET 5.0 SDK](https://dotnet.microsoft.com/download/dotnet/5.0)
I will address it in a separate PR as I want to double-check all workloads

2021-12-13 11:40 UTC, pellared commented on docs/CONTRIBUTING.md
> +1. You are working against the latest source on the `main` branch.
@Kielek I think we will change the branch `next-ver` to `main` and the current `main` to `legacy-main` as we did in OTel some time ago. I just do not know when it will happen 😄

2021-12-13 11:44 UTC, Kielek approved these changes

2021-12-13 11:48 UTC, pellared commented on docs/README.md
> +- .NET (Core) 3.1 and higher on Windows and Linux
@theletterf WDYT?

2021-12-13 11:56 UTC, theletterf requested changes

2021-12-13 11:56 UTC, theletterf commented on docs/INTERNAL_CONFIGURATION.md
>  | `SIGNALFX_APM_RECEIVER_PORT` | The port for Trace Agent binding. | `8126` |
@pellared I'd argue that this doc should be deleted or moved to DEVELOPING.md.

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +command session.
Not sure if this warning is required:

- What is the risk for users not setting the scope properly?
- How likely it is that users may set the scope incorrectly?
- What's the preferred way to set the env vars here? I see you use `setx`, but that's permanent. Do we want to set the env vars permanently? Why not using `$env:` like we do for Java and Python?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +system where it will be running.
```suggestion
1. Download and run the .MSI installer of the CLR Profiler for your architecture.
```

@pellared Can we add more or less permanent links to each arch installer? We want to users to quickly grab the file from the docs. Alternatively, can we provide a PowerShell `Invoke-WebRequest` snippet that does everything (download, silent install, etc.)? 

Also, what's the CLR Profiler in this context? Is it equivalent to the Java agent for autoinstrumentation?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +    setx COR_PROFILER "{B4C89B0F-9908-4F73-9F59-0D77C5A06874}" /m
What does that value do?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +   setx CORECLR_PROFILER "{B4C89B0F-9908-4F73-9F59-0D77C5A06874}" /m
Let's consider automating all these steps in a PowerShell script/snippet?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +   setx SIGNALFX_ENDPOINT_URL http://localhost:9411/api/v2/spans /m
What's the default value? Couldn't we set a default for this to avoid an additional step?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +## Requirements
I think we haven't mentioned that a Splunk OTel Collector instance must be up and running in the host.

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +- .NET Framework 4.6.2 and higher on Windows
This includes mono?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +1. Optionally, enable trace injection in logs:
I'd add a link here to the logs injection instructions.

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +## Manually instrument an application
I'd move this to docs/manual-instrumentation.md

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +## Troubleshooting
Let's move this to docs/troubleshooting.md

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +    ```
Not entirely familiar with .NET dependency system. Does this require the download of a NuGet package? If a previous download or import step is required, we should describe it here.

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +
The rest of ENV vars would be configured the same as with the autoinstrumentation?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +1. Enable instrumentation for the targeted application by setting
Is this for AlwaysOn Profiling?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +   - For a specific user
I understand that instrumenting for the current command session is preferred in most cases. Under which cases would you instrument for a specific service or user? What's the consequence of instrumenting at user level?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +like [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer).
Isn't `dir env:` quicker?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +#### Enable instrumentation at different levels
Let's consider moving this page to docs/instrumentation-levels.md

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +Enable instrumentation for a specific Windows service:
For each level, let's provide an example and/or explain why one would select that option over the others.

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +   setx SIGNALFX_SERVICE my-service-name /m
We need also snippets for bash (Linux) in the official docs.

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +- For .NET Framework applications:
All these instructions are only for Windows?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +   ```
No Linux equivalent?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +1. Download the latest release of the library.
How? Can we provide a `curl` snippet here?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +1. Download the latest release of the library.
Where is the library installed or where should it be installed? How does it interact with the CLR Profiler?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +    ```
Can we join both steps if related? I guess you can't enable logs injection if you don't have a logging dir.

Also, don't you need to create a dir in Windows, too? Or it just uses the built-in Event log?

2021-12-13 11:56 UTC, theletterf commented on docs/README.md
> +    ```
What should the user see in the stdout if the instrumentation has been successful?

2021-12-13 11:56 UTC, theletterf commented on docs/advanced-config.md
> +There are following ways to apply configuration settings
```suggestion
You can apply configuration settings in the following ways
```

2021-12-13 11:56 UTC, theletterf commented on docs/advanced-config.md
> +(prioritized from top to bottom):
```suggestion
, by order of preference:
```

2021-12-13 11:56 UTC, theletterf commented on docs/advanced-config.md
> +    A setting configured via an environment variable cannot be overridden.
```suggestion
Settings configured using environment variables always take precedence.
```

There are several ways of configuring env vars in Windows. Can we provide two sample snippets for PowerShell and Linux?

2021-12-13 11:56 UTC, theletterf commented on docs/advanced-config.md
> +    or application configuration file (`app.config`) can be used to configure settings.
```suggestion
    For an application running on .NET Framework, you can use a web configuration file 
    (`web.config`) or an application configuration file (`app.config`) to configure settings.
```

2021-12-13 11:56 UTC, theletterf commented on docs/advanced-config.md
> +    ```xml
Do XML settings take precedence over JSON config files?

2021-12-13 11:56 UTC, theletterf commented on docs/advanced-config.md
> +    To use it, set environment variable `SIGNALFX_TRACE_CONFIG_FILE`
Any hint as to why would someone prefer this method over XML?

2021-12-13 11:56 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_SAMPLE_RATE` | The global rate for the sampler. |  |
No default?

2021-12-13 11:58 UTC, pellared commented on docs/README.md
> +command session.
I totally agree
This is why I already marked in "Next Steps" in PR description: 

> simplify the Get started for Windows. some stuff should go to advanced configuration

2021-12-13 11:58 UTC, theletterf commented on docs/README.md
> +## Supported .NET versions
Any requirement in terms of Windows versions or Linux distros?

2021-12-13 11:59 UTC, pellared commented on docs/INTERNAL_CONFIGURATION.md
>  | `SIGNALFX_APM_RECEIVER_PORT` | The port for Trace Agent binding. | `8126` |
I would consider deleting it

@RassK @Kielek @dszmigielski @lachmatt WDYT? Any preference?

2021-12-13 12:00 UTC, pellared commented on docs/README.md
> +system where it will be running.
Let's address it in a separate PR

2021-12-13 12:00 UTC, pellared commented on docs/README.md
> +    setx COR_PROFILER "{B4C89B0F-9908-4F73-9F59-0D77C5A06874}" /m
https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/setting-up-a-profiling-environment 😉 .NET Profiling configuration is awkward 😋

2021-12-13 12:03 UTC, pellared commented on docs/README.md
> +   setx CORECLR_PROFILER "{B4C89B0F-9908-4F73-9F59-0D77C5A06874}" /m
instead of the batch script (Windows command prompt)? or in addition to it?

_added to TODO list_

2021-12-13 12:04 UTC, pellared commented on docs/README.md
> +   setx SIGNALFX_ENDPOINT_URL http://localhost:9411/api/v2/spans /m
We can but we need to implement it 😄 
Jira story created

2021-12-13 12:06 UTC, pellared commented on docs/README.md
> +## Requirements
You are correct. Let me add it in next PR

2021-12-13 12:08 UTC, pellared commented on docs/README.md
> +- .NET Framework 4.6.2 and higher on Windows
No. Maybe it would work but who knows 😄

2021-12-13 12:10 UTC, pellared commented on docs/README.md
> +1. Enable instrumentation for the targeted application by setting
AlwaysOn Profiling is not implemented yet

2021-12-13 12:10 UTC, pellared commented on docs/README.md
> +   - For a specific user
I agree with you. I want to update this whole section in a dedicated PR.

2021-12-13 12:13 UTC, pellared commented on docs/README.md
> +like [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer).
Process Explorer is better as it shows exact env vars used by the process. So it can be checked e.g. after a terminal that started the app is closed.

2021-12-13 12:13 UTC, pellared commented on docs/README.md
> +#### Enable instrumentation at different levels
I am thinking about a section in `advanced-configuration.md`. WDYT?

2021-12-13 12:14 UTC, pellared commented on docs/README.md
> +   setx SIGNALFX_SERVICE my-service-name /m
There are there, am I correct?

2021-12-13 12:15 UTC, pellared commented on docs/README.md
> +- For .NET Framework applications:
Yes

2021-12-13 12:16 UTC, pellared commented on docs/README.md
> +   ```
There are there in a section below. Am I correct?

2021-12-13 12:17 UTC, pellared commented on docs/README.md
> +1. Download the latest release of the library.
In fact, it is a CLR Profiler. I will double-check the installation later.

2021-12-13 12:19 UTC, pellared commented on docs/README.md
> +    ```
trace injection is for application logs
the logging directory is only for auto instrumentation logs 
these are different log destinations

the MSI creates the log directory on Windows
I will check if it is needed on Linux but as I remember it really was

2021-12-13 12:20 UTC, pellared commented on docs/README.md
> +    ```
I think he will only see that everything is OK by inspecting the logs...

2021-12-13 12:20 UTC, pellared commented on docs/advanced-config.md
> +    ```xml
yes they do

2021-12-13 12:21 UTC, theletterf commented on docs/README.md
> +- .NET (Core) 3.1 and higher on Windows and Linux
Ok for me! I wouldn't add links though.

2021-12-13 12:22 UTC, pellared commented on docs/advanced-config.md
> +    To use it, set environment variable `SIGNALFX_TRACE_CONFIG_FILE`
I think that `app.config` and `web.config` is working OOTB only on .NET Framework. So XML is rather for .NET (Core) applications. @RassK @Kielek am I correct?

2021-12-13 12:33 UTC, RassK commented on docs/advanced-config.md
> +    To use it, set environment variable `SIGNALFX_TRACE_CONFIG_FILE`
Currently I would say JSON is a backup option for .NET core stuff. It's easier to set local environment variables when running .net core,  so I guess env's will be still primary.

2021-12-13 12:33 UTC, pellared commented on docs/README.md
> +
Yes. This manual instrumentation will use all the settings applied by env vars (and other sources).

2021-12-13 12:45 UTC, pellared commented on docs/advanced-config.md
> +    To use it, set environment variable `SIGNALFX_TRACE_CONFIG_FILE`
The only scenario I see is when a .NET 5.0 app is deployed IIS. @RassK does it make sense?

2021-12-13 14:02 UTC, RassK commented on docs/advanced-config.md
> +    To use it, set environment variable `SIGNALFX_TRACE_CONFIG_FILE`
I can't think of any necessary scenario atm. With .NET Core you can always scope envs locally, even when hosting in IIS. (I think newer IIS is still reusing the .NET Core feature to set envs).

Might be just for some kind of CI, that works better with JSON.

2021-12-14 07:38 UTC, pellared commented on docs/README.md
> +- .NET Framework 4.6.2 and higher on Windows
I have done quick research (but just reading - not testing) and it seems that it would not work on Mono.

2021-12-14 07:39 UTC, Kielek commented on docs/INTERNAL_CONFIGURATION.md
>  | `SIGNALFX_APM_RECEIVER_PORT` | The port for Trace Agent binding. | `8126` |
If we do not delete usages (and it could be expensive). It will be great to have list of non-supported env. variables in one place.
The place (DEVELOPING.md/INTERNAL_CONFIGURATION.md) is not so important.

2021-12-14 09:10 UTC, pellared commented on docs/README.md
> +- .NET (Core) 3.1 and higher on Windows and Linux
Addressed https://github.com/signalfx/signalfx-dotnet-tracing/pull/251/commits/e7bb46857796f6cb3b430d94852441e272119e50

2021-12-14 09:16 UTC, pellared commented on docs/INTERNAL_CONFIGURATION.md
>  | `SIGNALFX_APM_RECEIVER_PORT` | The port for Trace Agent binding. | `8126` |
I feel the same. It saves us time if we want to make double-check if have forgotten to document some setting or if it is not supported by design. Addressed 28c70442

2021-12-14 09:17 UTC, pellared commented on docs/README.md
> +Enable instrumentation for a specific Windows service:
I will address it in a separate PR

2021-12-14 09:19 UTC, pellared commented on docs/README.md
> +    ```
Postponed for a seperate PR

2021-12-14 09:19 UTC, pellared commented on docs/README.md
> +    ```
I will address it in a separate PR

2021-12-14 09:28 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_SAMPLE_RATE` | The global rate for the sampler. |  |
When not assigned there then it is always sampling. I will try to address it in a separate PR.

2021-12-14 09:30 UTC, pellared commented on docs/README.md
> +## Supported .NET versions
I will try to investigate if we have any official list of if we try to support whatever is possible.

2021-12-14 10:03 UTC, merged