[WIP] Add IIS instrumentation docs
signalfx/signalfx-dotnet-tracing pull request #271
Opened 2021-12-17 11:46 UTC by RassK

## What

Adds IIS instrumentation docs

2021-12-17 13:12 UTC, theletterf requested changes

2021-12-17 13:12 UTC, theletterf commented on docs/iis-instrumentation.md
> +By default Windows installer enables IIS instrumentation by setting `Environment` registry key for W3SVC and WAS services located in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services` folder.
```suggestion
By default, the installer enables IIS instrumentation by setting the `Environment` registry key for W3SVC and WAS services located in the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services` folder.
```

2021-12-17 13:12 UTC, theletterf commented on docs/iis-instrumentation.md
> +Additional local configuration is necessary if you are running multiple applications on a single server (such as IIS server with multiple web apps). This helps to set application specific behavior (s
```suggestion
Additional local configuration is necessary if you are running multiple applications on a single server (such as IIS server with multiple web apps). This helps set application specific behavior (such as setting service name via `SIGNALFX_SERVICE_NAME`). Local configuration has higher precedence than global (machine level) configuration and will overwrite global values. Note that machine-level environment values affect every .NET application on that server.
```

2021-12-17 13:12 UTC, theletterf commented on docs/iis-instrumentation.md
> +Local configuration for .NET Framework apps can be done via updating `web.config`. See [advanced-config.md](advanced-config.md#configuration-methods) for syntax.
```suggestion
Local configuration for .NET Framework apps can be done by updating the `web.config` file. See [advanced-config.md](advanced-config.md#configuration-methods) for more information.
```

2021-12-17 13:12 UTC, theletterf commented on docs/iis-instrumentation.md
> +Please follow [Microsoft guide](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#set-the-environment) how to set additional local environment variables for .
```suggestion
See the [Microsoft guide](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#set-the-environment) on how to set additional local environment variables for .NET Core apps.
```

2021-12-27 08:11 UTC, pellared reviewed
Nice 👍 Just left a few comments.

Can you consider splitting the long lines into several lines?
I have added a configuration for `markdownlint` some time ago - you can use this VS Code extension to see the warnings: https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

I consider to add a GH workflow to check to run `markdownlint` and `misspell` linters 😉

2021-12-27 08:11 UTC, pellared commented on docs/iis-instrumentation.md
> +By default, the installer enables IIS instrumentation by setting the `Environment` registry key for W3SVC and WAS services located in the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services` folder
```suggestion
By default, the installer enables IIS instrumentation for .NET Framework
 by setting the `Environment` registry key for W3SVC and WAS services
 located in the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services` folder.
```

2021-12-27 08:11 UTC, pellared commented on docs/iis-instrumentation.md
> +Additional local configuration is necessary if you are running multiple applications on a single server (such as IIS server with multiple web apps). This helps set application specific behavior (such
**IMPORTANT**
Is it not required to set `CORECLR_ENABLE_PROFILING` and `CORECLR_PROFILER` for .NET (Core)? The installer does not set these values. Personally I propose to update the installer to add these 😉

2021-12-27 08:11 UTC, pellared commented on docs/iis-instrumentation.md
> +### .NET Core
```suggestion
### .NET and .NET Core
```

2021-12-27 09:58 UTC, pellared commented on docs/iis-instrumentation.md
> +# IIS instrumentation
nit

```suggestion
# Instrument an ASP.NET application deployed on IIS
```

2021-12-28 09:54 UTC, Kielek commented on docs/iis-instrumentation.md
> +Additional local configuration is necessary if you are running multiple applications on a single server (such as IIS server with multiple web apps). This helps set application specific behavior (such
The statement in documentation is pretty clear. .NET Framework on IIS.

I do not think that .NET Core on IIS is common scenario. By default it is hosted on Kestrel instead of IIS.

If we speaking about CORECLR_ registry settings. I do not think that it is good idea to add it now. We should make some manual tests to provide it. @pellared , consider keep it as it is/create separate jira item.

2021-12-28 09:56 UTC, Kielek commented
> Can you consider splitting the long lines into several lines?

Done

2021-12-28 09:57 UTC, Kielek approved these changes

2021-12-28 10:16 UTC, theletterf approved these changes

2021-12-28 10:16 UTC, theletterf commented on docs/iis-instrumentation.md
> +applications on a single server (such as IIS server with multiple web apps).
```suggestion
applications on a single server (such as IIS server with multiple webapps).
```

2021-12-28 10:16 UTC, theletterf commented on docs/iis-instrumentation.md
> +This helps set application specific behavior (such as setting service name via `SIGNALFX_SERVICE_NAME`).
```suggestion
This helps set application-specific behavior (such as setting the service name via `SIGNALFX_SERVICE_NAME`).
```

2021-12-28 10:16 UTC, theletterf commented on docs/iis-instrumentation.md
> +Local configuration has higher precedence than global (machine level)
```suggestion
Local configuration has higher precedence than global (machine-level)
```

2021-12-28 10:16 UTC, theletterf commented on docs/iis-instrumentation.md
> +on that server.
```suggestion
on the server where they're defined.
```

2021-12-28 10:16 UTC, theletterf commented on docs/iis-instrumentation.md
> +Local configuration for .NET Framework apps can be done
```suggestion
Local configuration for .NET Framework apps can be edited
```

2021-12-28 10:18 UTC, theletterf approved these changes

2021-12-28 10:19 UTC, pellared commented on docs/iis-instrumentation.md
> +Additional local configuration is necessary if you are running multiple applications on a single server (such as IIS server with multiple web apps). This helps set application specific behavior (such
I propose to:

1. Remove the `### .NET and .NET Core` section
1. Remove the `.NET Framework` header (only the header - the content is OK)

After spending some time I do not think IIS instrumentation makes much sense (and probably it would not even work) for .NET (Core).

2021-12-28 10:21 UTC, pellared commented on docs/iis-instrumentation.md
> +This helps set application-specific behavior (such as setting the service name via `SIGNALFX_SERVICE_NAME`).
I think we should simply add a step to add `SIGNALFX_SERVICE_NAME` to the `web.config` file. In all our instrumentations (other languages/ecosystems and even in instructions how to instrument a normal all and Windows Service) we say that this setting should be set.

2021-12-28 11:17 UTC, pellared approved these changes

2021-12-28 11:39 UTC, merged