Add internal documentation for thread sampling
signalfx/signalfx-dotnet-tracing pull request #282
Opened 2021-12-23 06:32 UTC by Kielek

## Why

Keep internal doc up to date.

## What

Internal docs for `SIGNALFX_THREAD_SAMPLING_PERIOD` and `SIGNALFX_THREAD_SAMPLING_ENABLED`.

## Tests

N/A

2021-12-23 09:30 UTC, theletterf requested changes

2021-12-23 09:30 UTC, theletterf commented on docs/internal-config.md
> +| `SIGNALFX_METRICS_EXPORTER` | Metrics exporter to be used. The Tracer uses it to encode and dispatch metrics. Available values are: `SignalFx`, `StatsD`. | `SignalFx` |
```suggestion
| `SIGNALFX_METRICS_EXPORTER` | Metrics exporter to be used. The tracer uses it to encode and dispatch metrics. Available values are: `SignalFx`, `StatsD`. | `SignalFx` |
```

2021-12-23 09:30 UTC, theletterf commented on docs/internal-config.md
> +| `SIGNALFX_THREAD_SAMPLING_ENABLED` | Enable to activate thread sampling sent to SignalFx. | `false` |
```suggestion
| `SIGNALFX_THREAD_SAMPLING_ENABLED` | Enable to activate thread sampling. | `false` |
```

2021-12-23 09:30 UTC, theletterf commented on docs/internal-config.md
> +| `SIGNALFX_THREAD_SAMPLING_PERIOD` | Sampling period to be used. The Tracer uses it to stop threads for shorto amount of time and fetch all stack traces. This value cannot be lower that `1000` ms. |
```suggestion
| `SIGNALFX_THREAD_SAMPLING_PERIOD` | Sampling period. The tracer uses it to stop threads for a short amount of time and fetch all stack traces. This value cannot be lower that `1000` milliseconds. | `1000` |
```

2021-12-23 10:44 UTC, theletterf approved these changes

2021-12-27 07:58 UTC, pellared commented on docs/internal-config.md
> +| `SIGNALFX_METRICS_EXPORTER` | Metrics exporter to be used. The tracer uses it to encode and dispatch metrics. Available values are: `SignalFx`, `StatsD`. | `SignalFx` |
```suggestion
| `SIGNALFX_METRICS_EXPORTER` | Metrics exporter to be used. It is used to encode and dispatch metrics. Available values are: `SignalFx`, `StatsD`. | `SignalFx` |
```

I find the term `tracer` confusing. Especially that here we are talking about metrics. Not traces.

2021-12-27 07:58 UTC, pellared commented on docs/internal-config.md
> +| `SIGNALFX_THREAD_SAMPLING_PERIOD` | Sampling period. The tracer uses it to stop threads for a short amount of time and fetch all stack traces. This value cannot be lower that `1000` milliseconds. |
```suggestion
| `SIGNALFX_THREAD_SAMPLING_PERIOD` | Sampling period. It definess how often the threads are stopped in order to fetch all stack traces. This value cannot be lower than `1000` milliseconds. | `1000` |
```

I find the term `tracer` confusing. Especially that here we are talking about profiling. Not tracing.

2021-12-27 10:01 UTC, pellared approved these changes

2021-12-27 12:38 UTC, lachmatt approved these changes

2021-12-27 12:39 UTC, merged