Split advanced configuration settings into sections
signalfx/signalfx-dotnet-tracing pull request #294
Opened 2021-12-30 12:02 UTC by pellared

Split advanced configuration settings into sections

2021-12-30 15:21 UTC, theletterf requested changes

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +We highly suggest to configure the settings below.
```suggestion
The following settings are common to most instrumentation scenarios:
```

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_SERVICE_NAME` | Application's default service name. |  |
```suggestion
| `SIGNALFX_SERVICE_NAME` | The name of the application or service. |  |
```

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_VERSION` | The application's version that will populate `version` tag on spans. |  |
```suggestion
| `SIGNALFX_VERSION` | The version of the application. When set, it populates the `version` tag on spans. |  |
```

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_PROFILER_EXCLUDE_PROCESSES` | Sets the filename of executables the profiler cannot attach to. If not defined (default), the profiler will attach to any process. Supports multiple values s
```suggestion
| `SIGNALFX_PROFILER_EXCLUDE_PROCESSES` | Sets the filename of executables the profiler cannot attach to. Supports multiple comma-separated values, for example: `MyApp.exe,dotnet.exe` |  |
```

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_PROFILER_PROCESSES` | Sets the filename of executables the profiler can attach to. If not defined (default), the profiler will attach to any process. Supports multiple values separated wi
```suggestion
| `SIGNALFX_PROFILER_PROCESSES` | Sets the filename of executables the profiler can attach to. Supports multiple comma-separated values, for example: `MyApp.exe,dotnet.exe` |  |
```

How does this one and `SIGNALFX_PROFILER_EXCLUDE_PROCESSES`  interact? Can they be used simultaneously? What happens if a process is in both lists? Is any of these lists required?

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_CONFIG_FILE` | The file path of a JSON configuration file that will be loaded. |  |
```suggestion
| `SIGNALFX_TRACE_CONFIG_FILE` | Path of the JSON configuration file. |  |
```

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_RECORDED_VALUE_MAX_LENGTH` | The maximum length an attribute value can have. Values longer than this are truncated. Values are completely truncated when set to 0, and ignored when set to
```suggestion
| `SIGNALFX_RECORDED_VALUE_MAX_LENGTH` | The maximum length an attribute value can have. Values longer than this are truncated. Values are discarded entirely when set to 0, and ignored when set to a negative value. | `12000` |
```

What's the difference between ignored and truncated completely or discarded?

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_TAGS` | Comma-separated list of key-value pairs to specify global span tags. For example: `"key1:val1,key2:val2"` |  |
```suggestion
| `SIGNALFX_TAGS` | Comma-separated list of key-value pairs that specify global span tags. For example: `"key1:val1,key2:val2"` |  |
```

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_{0}_ENABLED` | Configuration pattern for enabling or disabling a specific library instrumentation. For example, in order to disable Kafka instrumentation, set `SIGNALFX_TRACE_Kafka_
Might be convenient to link to a list of instrumentation names somewhere.

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_HTTP_SERVER_ERROR_STATUSES` | The application's server http statuses to set spans as errors by. | `500-599` |
```suggestion
| `SIGNALFX_HTTP_CLIENT_ERROR_STATUSES` | The application's client http statuses to set spans as errors by. | `400-599` |
| `SIGNALFX_HTTP_SERVER_ERROR_STATUSES` | The application's server http statuses to set spans as errors by. | `500-599` |
```

Description is unclear. How does one use these? Are admitted values in the form of `[1-9]{3}-[1-9]{3}` ranges?

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_INSTRUMENTATION_ELASTICSEARCH_TAG_QUERIES` | Enable the tagging of a Elasticsearch command PostData as `db.statement`. It may introduce overhead for direct streaming users. | `true` |
```suggestion
| `SIGNALFX_INSTRUMENTATION_ELASTICSEARCH_TAG_QUERIES` | Enable the tagging of an Elasticsearch command PostData as `db.statement`. It might introduce overhead for direct streaming users. | `true` |
```

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_LOGS_INJECTION` | Enable to inject trace IDs, span IDs, service name and environment into logs. This requires a compatible logger or manual configuration. | `false` |
```suggestion
| `SIGNALFX_LOGS_INJECTION` | Enable to inject trace IDs, span IDs, service name, and environment into logs. This requires a compatible logger or manual configuration. | `false` |
```

What's the list of compatible loggers? See, for instance, how our OTel Java docs deal with this: 

https://github.com/signalfx/splunk-otel-java/blob/main/docs/correlating-traces-with-logs.md

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_HEADER_TAGS` | Comma-separated map of HTTP header keys to tag name, that will be automatically applied as tags on traces. | `"x-my-header:my-tag,header2:tag2"` |
```suggestion
| `SIGNALFX_TRACE_HEADER_TAGS` | Comma-separated map of HTTP header keys to tag names, automatically applied as tags on traces. | `"x-my-header:my-tag,header2:tag2"` |
```

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_RESPONSE_HEADER_ENABLED` | Enable to add server trace information to HTTP response headers. | `true` |
```suggestion
| `SIGNALFX_TRACE_RESPONSE_HEADER_ENABLED` | Enable to add server trace information to HTTP response headers. | `true` |
```

Shall we say that this enables the integration with Splunk RUM?

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_FILE_LOG_ENABLED` | Enable file logging. This is enabled by default. | `true` |
```suggestion
| `SIGNALFX_FILE_LOG_ENABLED` | Enable file logging. | `true` |
```

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_MAX_LOGFILE_SIZE` | The maximum size for tracer log files, in bytes. | `10 MB` |
The default doesn't seem expressed in bytes. :P What's the form for this string?

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_STDOUT_LOG_ENABLED` | Enables `stdout` logging. This is disabled by default. | `false` |
```suggestion
| `SIGNALFX_STDOUT_LOG_ENABLED` | Enables `stdout` logging. | `false` |
```

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_DEBUG` | Enable to activate debugging mode for the tracer. | `false` |
We may want to explain in a `troubleshooting.md` file how to configure debug logging all these options.

2021-12-30 15:21 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_LOG_PATH` | (Deprecated) The path of the profiler log file. | Linux: `/var/log/signalfx/dotnet/dotnet-profiler.log`<br>Windows: `%ProgramData%\SignalFx .NET Tracing\logs\dotnet-prof
If this one's deprecated, let's move it at the end of the table.

2021-12-30 15:21 UTC, theletterf commented on docs/troubleshooting.md
> +Enable debug logging If none of the suggestions solved your issue.
```suggestion
Enable debug logging if none of the suggestions solved your issue.
```

2021-12-30 15:32 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_{0}_ENABLED` | Configuration pattern for enabling or disabling a specific library instrumentation. For example, in order to disable Kafka instrumentation, set `SIGNALFX_TRACE_Kafka_
```suggestion
| `SIGNALFX_TRACE_{0}_ENABLED` | Configuration pattern for enabling or disabling a specific [library instrumentation](instrumented-libraries.md). For example, in order to disable Kafka instrumentation, set `SIGNALFX_TRACE_Kafka_ENABLED=false` | `true` |
```

2021-12-30 15:33 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_HTTP_SERVER_ERROR_STATUSES` | The application's server http statuses to set spans as errors by. | `500-599` |
integers separated with `-`

2021-12-30 15:35 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_LOGS_INJECTION` | Enable to inject trace IDs, span IDs, service name and environment into logs. This requires a compatible logger or manual configuration. | `false` |
Updated your suggestion

2021-12-30 15:37 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_RESPONSE_HEADER_ENABLED` | Enable to add server trace information to HTTP response headers. | `true` |
Yup 👍 I look at Java and Python distros to check how they described it.

2021-12-30 15:38 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_MAX_LOGFILE_SIZE` | The maximum size for tracer log files, in bytes. | `10 MB` |
I will check it

2021-12-30 15:39 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_LOG_PATH` | (Deprecated) The path of the profiler log file. | Linux: `/var/log/signalfx/dotnet/dotnet-profiler.log`<br>Windows: `%ProgramData%\SignalFx .NET Tracing\logs\dotnet-prof
Or maybe just remove it? 😄 WDYT? We can move it to `internal-config.md` as a deprecated configuration.

2021-12-30 16:04 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_DEBUG` | Enable to activate debugging mode for the tracer. | `false` |
The most important configuration is described here: https://github.com/signalfx/signalfx-dotnet-tracing/blob/next-ver/docs/troubleshooting.md#investigating-other-issues

Do you find it good enough?

2021-12-30 16:05 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_DEBUG` | Enable to activate debugging mode for the tracer. | `false` |
Let's use that for now!

2021-12-30 16:07 UTC, theletterf requested changes

2021-12-30 16:07 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_HTTP_SERVER_ERROR_STATUSES` | The application's server http statuses to set spans as errors by. | `500-599` |
And what's the use case? Which errors range can be captured for each? Shouldn't the default for client errors stop at `499`?

2021-12-30 16:07 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_RESPONSE_HEADER_ENABLED` | Enable to add server trace information to HTTP response headers. | `true` |
Could we create a simple page for this like those where we also explain which libraries are compatible?

2021-12-30 16:07 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_LOG_PATH` | (Deprecated) The path of the profiler log file. | Linux: `/var/log/signalfx/dotnet/dotnet-profiler.log`<br>Windows: `%ProgramData%\SignalFx .NET Tracing\logs\dotnet-prof
Agree!

2021-12-30 16:08 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_LOG_PATH` | (Deprecated) The path of the profiler log file. | Linux: `/var/log/signalfx/dotnet/dotnet-profiler.log`<br>Windows: `%ProgramData%\SignalFx .NET Tracing\logs\dotnet-prof
Yeah. The changelog already says that it is deprecated.

2021-12-30 16:12 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_HTTP_SERVER_ERROR_STATUSES` | The application's server http statuses to set spans as errors by. | `500-599` |
I see that it is comma-seperated ranges of `[0-9]{3}` values...

e.g. `202,300-311,400-599` ...

2021-12-30 16:15 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_LOG_PATH` | (Deprecated) The path of the profiler log file. | Linux: `/var/log/signalfx/dotnet/dotnet-profiler.log`<br>Windows: `%ProgramData%\SignalFx .NET Tracing\logs\dotnet-prof
Addressed 6126231d

2021-12-30 16:23 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_HTTP_SERVER_ERROR_STATUSES` | The application's server http statuses to set spans as errors by. | `500-599` |
```suggestion
| `SIGNALFX_HTTP_CLIENT_ERROR_STATUSES` | Comma-separated list of HTTP client response statuses for which the spans are set as errors, for example: `300, 400-499`.  | `400-599` |
| `SIGNALFX_HTTP_SERVER_ERROR_STATUSES` | Comma-separated list of HTTP server response statuses for which the spans are set as errors, for example: `300, 400-599`. | `500-599` |
```

2021-12-30 16:26 UTC, theletterf commented on docs/advanced-config.md
> +| `SIGNALFX_HTTP_SERVER_ERROR_STATUSES` | The application's server http statuses to set spans as errors by. | `500-599` |
Love it!

2021-12-30 16:26 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_MAX_LOGFILE_SIZE` | The maximum size for tracer log files, in bytes. | `10 MB` |
```suggestion
| `SIGNALFX_MAX_LOGFILE_SIZE` | The maximum size for tracer log files, in bytes. | `245760` (10 MB) |
```

2021-12-30 16:26 UTC, theletterf approved these changes

2021-12-30 16:41 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_RESPONSE_HEADER_ENABLED` | Enable to add server trace information to HTTP response headers. | `true` |
```suggestion
| `SIGNALFX_TRACE_RESPONSE_HEADER_ENABLED` | Enable to add server trace information to HTTP response headers. It enables [Splunk Real User Monitoring (RUM)](https://www.splunk.com/en_us/observability/real-user-monitoring.html) integration when using ASP.NET and ASP.NET Core. | `true` |
```

Not sure if it is worth to create a page. Put if you think it will be better then we can create one.

2021-12-30 16:46 UTC, pellared commented on docs/advanced-config.md
> +| `SIGNALFX_TRACE_RESPONSE_HEADER_ENABLED` | Enable to add server trace information to HTTP response headers. | `true` |
Addressed https://github.com/signalfx/signalfx-dotnet-tracing/pull/294/commits/a9d2c8a30c6ec87bc3338c60cb05fb8ccf945c99

2021-12-30 17:45 UTC, theletterf approved these changes

2021-12-31 08:10 UTC, theletterf approved these changes

2021-12-31 08:46 UTC, lachmatt approved these changes

2021-12-31 08:46 UTC, merged