Add azure docs
signalfx/signalfx-dotnet-tracing pull request #299
Opened 2022-01-05 16:54 UTC by RassK

## What

Adds Azure Web Service instrumentation instructions. 

## Tests

Repeated steps in Azure. 
https://app.signalfx.com/#/apm/traces/533732f193fcb568c6380a6441b381f2

## Next 

Any ideas does it cover webjobs or they require something more special?

2022-01-05 19:12 UTC, Kielek commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
Could you please be more specific which environmental variables are mandatory?
In previous document three of them was marked in this way `SIGNALFX_SERVICE_NAME`, `SIGNALFX_ACCESS_TOKEN` and  `SIGNALFX_ENDPOINT_URL`.

2022-01-05 19:31 UTC, pellared commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
And probably it is worth saying that `SIGNALFX_ACCESS_TOKEN` and `SIGNALFX_ENDPOINT_URL` should be set in a way to send the telemetry directly to the Splunk Observability Cloud.

2022-01-05 19:31 UTC, pellared commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
Also, I think a step like `Restart your App Service.` is missing at the end.

2022-01-05 19:34 UTC, pellared commented on docs/azure.md
> +# Azure services instrumentation guide
```suggestion
# Azure instrumentation guide
```

WDYT? to keep in sync with the header from `README.md`

2022-01-05 19:37 UTC, pellared commented on docs/README.md
> +## Azure instrumentation guide
```suggestion
## Instrument Azure App Service
```

the header would be similar to other headers

also, it is similar to: https://docs.signalfx.com/en/latest/apm/apm-instrument/apm-azure-app.html

2022-01-05 19:37 UTC, pellared commented on docs/azure.md
> +## App Service
```suggestion
# Instrument Azure App Service
```

to have the same title as the header in `README.md`

2022-01-05 19:38 UTC, pellared commented on docs/azure.md
> +3. Find and install `SignalFx .NET Tracing` extension.
```suggestion
3. Find and install the `SignalFx .NET Tracing` extension.
```

2022-01-05 20:04 UTC, Kielek commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
As I remember, `SIGNALFX_ACCESS_TOKEN` is mandatory. Otherwise, profiling for Azure App Service won't work.
We can change it - requierments from upstream.

2022-01-05 21:08 UTC, pjanotti commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
@RassK Include setting `SIGNALFX_AZURE_APP_SERVICES` to true.

2022-01-05 21:15 UTC, RassK commented on docs/README.md
> +## Azure instrumentation guide
It was actually intentionally named more generally, it might need more sections about different services.

2022-01-05 21:17 UTC, RassK commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
SIGNALFX_ACCESS_TOKEN and SIGNALFX_ENDPOINT_URL are the bare minimum to make it work. 
SIGNALFX_AZURE_APP_SERVICES is setup by the extension already.

Applying settings will restart the service anyway (at least it did for me).

2022-01-05 21:30 UTC, pjanotti commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
> SIGNALFX_AZURE_APP_SERVICES is setup by the extension already.

ops, forgot about that...

2022-01-05 23:12 UTC, pellared commented on docs/README.md
> +## Azure instrumentation guide
if it happens then we will change it  😉

2022-01-06 10:38 UTC, RassK commented on docs/README.md
> +## Azure instrumentation guide
Well, that's why the question about Webjobs also. I might have to test it then. I guess AWS would get similar layout, if I remember right, there are web and serverless components as a separate service.

2022-01-06 16:04 UTC, RassK commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
> > SIGNALFX_AZURE_APP_SERVICES is setup by the extension already.
> 
> ops, forgot about that...

@pjanotti btw, just discovered that `SIGNALFX_AZURE_APP_SERVICES=1` is effectively disabling WebJobs instrumentation by mistakenly thinking it's infrastructure service.  Also non of the ENVs set by the extension are effective for WebJobs. By manually adding envs and `SIGNALFX_AZURE_APP_SERVICES=0` at least profiler attaches.

2022-01-07 18:31 UTC, pjanotti commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
@RassK I don't understand why this happens, do you know the details?

2022-01-10 13:25 UTC, RassK commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
@pjanotti I think it's because Webjobs are executed in Kudu scm context (has it's own w3wp process), while actual web service generates second w3wp process. 
https://github.com/signalfx/signalfx-dotnet-tracing/blob/next-ver/tracer/src/Datadog.Trace.ClrProfiler.Native/cor_profiler.cpp#L123

![image](https://user-images.githubusercontent.com/4929112/148773216-486d6f4c-49da-42c2-a385-fa2ac314cf4b.png)

2022-01-10 14:04 UTC, theletterf requested changes

2022-01-10 14:04 UTC, theletterf commented on docs/azure.md
> +5. Add `New application setting`s to configure receiver:
```suggestion
5. Add `New application settings` to configure the receiver: 
```

2022-01-10 18:44 UTC, pjanotti commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
@RassK I'm not that familiar with WebJobs, according to https://docs.microsoft.com/en-us/azure/app-service/webjobs-create#acceptablefiles it seems that one has to create the job as an exe to be something that we may want to instrument. It seems a very special case, at first, my instinct tells me to keep it as it is.

2022-01-11 01:29 UTC, RassK commented on docs/azure.md
> +5. Add `New application setting` to configure receiver. See [advanced-config.md](advanced-config.md#exporter-settings) exporter settings section for more details.
@pjanotti yep, a console with generic host + webjobs sdk. We can leave it as is, just document that all env's must be set manually and make sure azure one is set off. Then it works also, just not sure if it might attach something internal additionally or not.

2022-01-11 11:18 UTC, RassK commented on docs/azure.md
> +5. Add `New application setting`s to configure receiver:
The button name is actually in the singular, that's why the singular form is highlighted. Maybe just to rephrase entirely differently?

2022-01-11 11:33 UTC, pellared commented on docs/azure.md
> +5. Add `New application setting`s to configure receiver:
```suggestion
5. Add `New application setting` to configure the receiver: 
```

?

2022-01-11 12:05 UTC, RassK commented on docs/azure.md
> +<!-- TODO: What are the workarounds we can provide? -->
Anything we can suggest here? OTel.NET SDK seems to work here, but we don't have it vendored yet.

2022-01-11 12:05 UTC, RassK commented on docs/azure.md
> +<!-- TODO: What are the workarounds we can provide? -->
@pjanotti @pellared ⬆️

2022-01-11 12:16 UTC, RassK commented on docs/azure.md
> +## WebJobs (Experimental)
Marked as experimental for now... hopefully we will get some feedback once someone tries experimental stuff.

2022-01-11 17:57 UTC, pjanotti commented on docs/azure.md
> +<!-- TODO: What are the workarounds we can provide? -->
For AZ functions we can do https://github.com/signalfx/signalfx-dotnet-tracing#azure-function-custom-linux-docker-image

IIRC there is no way to install a profiler for Windows based functions.

2022-01-11 17:57 UTC, pjanotti commented on docs/azure.md
> +## WebJobs (Experimental)
I think it is better to record this info under internal. I'm not sure if there is demand for this capability.

2022-01-11 17:57 UTC, pjanotti commented on docs/azure.md
> +Repeat all of the App Service section steps. Currently environment configuration must be done manually. Specially notice that `SIGNALFX_AZURE_APP_SERVICES` must be disabled. It is strongly adviced to
I think that the right way to do this is to disable SIGNALFX_AZURE_APP_SERVICES for the scope of the WebJob process and call attention that if you do it for the whole box you will lose the instrumentation for the Web App.

2022-01-12 10:27 UTC, pellared commented
@RassK I propose to make separate PRs for different Azure integrations such us:
- Azure App Service
- Azure WebJobs
- Azure Functions

it will be easier to review one by one and merge.

2022-01-12 10:36 UTC, Kielek commented on docs/azure.md
> +## WebJobs (Experimental)
I agree, we have supported only App Serivices. As long as there is not such request we should put your documentation into internal-doc/jira tasks to write document for WebJobs.

It is good candidate for upstram sync phase 3.

2022-01-12 10:49 UTC, pellared commented on docs/azure.md
> +<!-- TODO: What are the workarounds we can provide? -->
I suggest postponing this (create a Jira story)

btw you can also find some dockerfiles here: https://github.com/signalfx/signalfx-dotnet-tracing/tree/next-ver/tracer/samples/ConsoleApp

2022-01-12 11:40 UTC, RassK commented
> @RassK I propose to make separate PRs for different Azure integrations such us:
> 
> * Azure App Service
> * Azure WebJobs
> * Azure Functions
> 
> it will be easier to review one by one and merge.

@pellared yep, seems discussions went bigger than I expected. I'll do separation.

2022-01-12 13:10 UTC, pellared approved these changes
few suggestions (one is a typo)

2022-01-12 13:10 UTC, pellared commented on docs/azure.md
> +# Azure services instrumentation guide
```suggestion
# Azure instrumentation guide
```

to match with main `README.md`

2022-01-12 13:10 UTC, pellared commented on docs/azure.md
> +5. Add `New application setting`s to configur the receiver:
```suggestion
5. Add `New application setting`s to configure the receiver:
```

2022-01-12 13:10 UTC, pellared commented on docs/azure.md
> +6. Make sure that App Service was restarted.
maybe simply:

```suggestion
6. Restart the App Service.
```

2022-01-12 14:27 UTC, merged