Add info about the default service name
signalfx/signalfx-dotnet-tracing pull request #300
Opened 2022-01-06 20:31 UTC by pjanotti

## Why

Especially for IIS configuring the `SIGNALFX_SERVICE_NAME` can be cumbersome to configure. We want to avoid this configuration if possible.

## What

Documenting the default service name and making the case that the user just needs to set it if the default doesn't work for their scenario.

## Tests

N/A (docs only)

2022-01-07 08:32 UTC, theletterf requested changes
Thanks! Just some nits.

2022-01-07 08:32 UTC, theletterf commented on docs/default-service-name.md
> +2. For an ASP.NET hosted application, eg.: IIS .NET Framework apps, the default service name is `SiteName[/VirtualPath]`.
```suggestion
2. For an ASP.NET hosted application, for example IIS .NET Framework apps, the default service name is `SiteName[/VirtualPath]`.
```

2022-01-07 08:32 UTC, theletterf commented on docs/default-service-name.md
> +4. In the unlikely case that the [entry assembly is not available](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getentryassembly?view=net-6.0#remarks).
```suggestion
4. If the [entry assembly is not available](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getentryassembly?view=net-6.0#remarks).
```

2022-01-07 08:32 UTC, theletterf commented on docs/iis-instrumentation.md
> +For ASP.NET applications (ie.: those IIS applications running on the .NET Framework) the
```suggestion
For ASP.NET applications, for example IIS applications running on the .NET Framework, the
```

2022-01-07 08:32 UTC, theletterf commented on docs/iis-instrumentation.md
> +If the defaults above don't fit well with your usage or naming conventions configure `SIGNALFX_SERVICE_NAME` as described in [advanced-config.md](advanced-config.md#configuration-methods).
```suggestion
If the defaults don't fit well with your usage or naming conventions configure `SIGNALFX_SERVICE_NAME` as described in [advanced-config.md](advanced-config.md#configuration-methods).
```

2022-01-07 18:44 UTC, pjanotti commented
Thanks for the suggestions @theletterf

2022-01-07 19:28 UTC, Kielek approved these changes

2022-01-09 20:02 UTC, pellared commented on docs/iis-instrumentation.md
> +default service name is `ServiceName[\VirtualPath]`.
Is it `ServiceName[\VirtualPath]` or `ServiceName[/VirtualPath]` ?

2022-01-10 09:08 UTC, theletterf approved these changes

2022-01-11 20:01 UTC, pjanotti commented on docs/iis-instrumentation.md
> +default service name is `ServiceName[\VirtualPath]`.
The second, will fix it before merging.

2022-01-11 21:13 UTC, pjanotti commented
Test run failure:
```terminal
Error: [xUnit.net 00:01:07.03]     Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.AssemblyLoadFileNotFoundExceptionSmokeTest.NoExceptions [FAIL]
    Failed Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.AssemblyLoadFileNotFoundExceptionSmokeTest.NoExceptions [1 m]
    Error Message:
     System.TimeoutException : The smoke test is running for too long or was lost.
    Stack Trace:
       at Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.SmokeTestBase.CheckForSmoke(Boolean shouldDeserializeTraces) in Y:\tracer\test\Datadog.Trace.ClrProfiler.IntegrationTests\SmokeTests\SmokeTestBase.cs:line 127
    Standard Output Messages:
   Application path: Y:\tracer\test/test-applications/regression\AssemblyLoad.FileNotFoundException\bin\X64\Release\net461\AssemblyLoad.FileNotFoundException.exe
   Executable path: Y:\tracer\test/test-applications/regression\AssemblyLoad.FileNotFoundException\bin\X64\Release\net461\AssemblyLoad.FileNotFoundException.exe
   Assigning port 50552 for the aspNetCorePort.
   Assigned port 50553 for the agentPort.
   The smoke test is running for too long or was lost.
   StandardOutput:
   All is well!
   ```

2022-01-12 00:15 UTC, merged