Manual instrumentation backwards compatibility
signalfx/signalfx-dotnet-tracing pull request #314
Opened 2022-01-13 13:15 UTC by dszmigielski

## Why

After the upstream rebase the manual instrumentation works differently than described in docs/manual-instrumentation.md.

## What

Bringing back the design on how manual instrumentation works from main branch

## Tests

New integration test was added, unit tests were added for new classes.

2022-01-13 13:25 UTC, pellared commented on tracer/src/Datadog.Trace/IDatadogOpenTracingTracer.cs
> +// <copyright file="IDatadogOpenTracingTracer.cs" company="Datadog">
`// Modified by SignalFx` comment missing 😄

2022-01-13 13:25 UTC, pellared commented on tracer/src/Datadog.Trace/Tracer.cs
> +                Log.Warning(ex, "Unable to load OpenTracing helper library.");
This will be always reported if the client does not reference `OpenTracing` in his application.
A workaround is to add the `OpenTracing.dll` to our installers. It was an issue reported by one of our clients.

2022-01-13 13:27 UTC, dszmigielski commented on tracer/src/Datadog.Trace/Tracer.cs
> +                Log.Warning(ex, "Unable to load OpenTracing helper library.");
Yep, is that a problem? I assume if they did not add `OpenTracing.dll` they are not using this, so it shouldn't matter for them.

2022-01-13 14:35 UTC, pellared requested changes
Do not forget to test it end-to-end using the installers/packages at least for Windows and Ubuntu 😉

2022-01-13 15:17 UTC, dszmigielski commented on tracer/src/Datadog.Trace/Tracer.cs
> +                Log.Warning(ex, "Unable to load OpenTracing helper library.");
I don't mind, but I would rather just change it to the INFO and leave the message as it is.

2022-01-13 16:03 UTC, pellared commented on tracer/src/Datadog.Trace/Tracer.cs
> +                Log.Warning(ex, "Unable to load OpenTracing helper library.");
`Unable to do something` may give a feeling that something is not fine. That is why I suggest rephrasing it.

2022-01-13 16:06 UTC, dszmigielski commented on tracer/src/Datadog.Trace/Tracer.cs
> +                Log.Warning(ex, "Unable to load OpenTracing helper library.");
Well, it's not something I'm willing to stand for too hard, I don't mind changing it as long as others find it a good solution, too :)

2022-01-13 19:52 UTC, dszmigielski commented on tracer/src/Datadog.Trace/Tracer.cs
> +                Log.Warning(ex, "Unable to load OpenTracing helper library.");
I have changed it to
```csharp
Log.Information(ex, "OpenTracing integration was not loaded.");
```
for now

2022-01-13 19:52 UTC, dszmigielski commented on tracer/src/Datadog.Trace/Tracer.cs
> +                var signalFxOpenTracingAssembly = Assembly.Load(new AssemblyName("SignalFx.Tracing.OpenTracing, Version=0.2.0.0, Culture=neutral, PublicKeyToken=e43a27c2023d388a"));
👍 done

2022-01-14 09:21 UTC, pellared commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingScopeManager.cs
> +using OpenTracing;
nit: can you add a blank line for consistency?

2022-01-14 09:21 UTC, pellared commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingTracer.cs
> +            : this(datadogTracer, new OpenTracingScopeManager(datadogTracer.ScopeManager))
can you please explain why we are changing this?

is it to support code like below?

```csharp
            var signalFxScope = _signalFxTracer.StartActive("testSpan");
            var openTracingScope = new OpenTracingScope((Scope)signalFxScope);
```

if so then do we need it? it is not documented in `manual-instrumentation.md` nor I cannot find it in https://github.com/signalfx/tracing-examples/tree/main/dotnet-manual-instrumentation

2022-01-14 10:11 UTC, Kielek commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingScopeManager.cs
> +// Modified by SignalFx
```suggestion
// Modified by Splunk Inc.

```

2022-01-14 21:16 UTC, pjanotti commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingScopeManager.cs
> +            return new OpenTracingScope(ScopeManager.Activate(((OpenTracingSpan)span).Span, finishSpanOnDispose));
Do we need to worry if `span` is `null` here?

2022-01-14 21:16 UTC, pjanotti commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingTracerFactory.cs
> +        private static readonly object Lock = new();
I don't think this lock is necessary: since we are dealing with the statics of OpenTracing for the registration I doubt that that code doesn't have a lock already - double check my assumption, please.

2022-01-14 21:16 UTC, pjanotti commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingTracerFactory.cs
> +        private static readonly object Lock = new();
I took a quick look there and it seems protected, it also seems that `RegisterIfAbsent` is actually a better method to be called below, see https://github.com/opentracing/opentracing-csharp/blob/461c6edd7b4209fe353eea7b927dd7046986e2b8/src/OpenTracing/Util/GlobalTracer.cs#L75

2022-01-14 21:16 UTC, pjanotti commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingTracerFactory.cs
> +        private static readonly object Lock = new();
Anyway, double check I looked at it very quickly.

2022-01-17 08:02 UTC, dszmigielski commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingScopeManager.cs
> +            return new OpenTracingScope(ScopeManager.Activate(((OpenTracingSpan)span).Span, finishSpanOnDispose));
As for how we are using it right now - nope

2022-01-17 08:12 UTC, dszmigielski commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingTracer.cs
> +            : this(datadogTracer, new OpenTracingScopeManager(datadogTracer.ScopeManager))
Well yeah, that's an overkill. I will revert that

2022-01-17 09:14 UTC, pellared approved these changes
minor comments only

2022-01-17 09:14 UTC, pellared commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingTracerFactory.cs
> +            return GlobalTracer.RegisterIfAbsent(WrapTracer(tracer));
Why we are using `RegisterIfAbsent`? Do we want to log something if it returns `false`? Maybe we should log that it was already registered?

Otherwise, we could use `GlobalTracer.Register`

Shouldn't the method be named `RegisterGlobalTracerIfAbsent` to follow the OpenTracing convention?

2022-01-17 09:14 UTC, pellared commented on tracer/test/Datadog.Trace.OpenTracing.Tests/OpenTracingTracerTests.cs
> +        }
nit:
we do not have to reuse `_signalFxTracer` -> we can create any new tracer instance. I have lost a few minutes to think why we are reusing `_signalFxTracer` here and I see no reason 😉 

also I am not sure what is the value of this test

2022-01-17 09:49 UTC, dszmigielski commented on tracer/test/Datadog.Trace.OpenTracing.Tests/OpenTracingTracerTests.cs
> +        }
I mean, the code is clearer if I don't have to create it every time. Especially that I would need some of the values needed to create one to be private fields then.

2022-01-17 10:40 UTC, pellared commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingTracerFactory.cs
> +            return GlobalTracer.RegisterIfAbsent(WrapTracer(tracer));
what do you think about adding a log line when it returns `false` and renaming the method?

2022-01-17 10:42 UTC, pellared commented on tracer/test/Datadog.Trace.OpenTracing.Tests/OpenTracingTracerTests.cs
> +        }
> I mean, the code is clearer if I don't have to create it every time.

I disagree b/c currently, I think that there is a reason that this tracer is reused.
You can always extract a method to create the `signalFxTracer` to a method to reduce the code duplication.

still it is not a blocker for me 😉

2022-01-17 12:17 UTC, pellared commented on tracer/src/Datadog.Trace.OpenTracing/OpenTracingTracerFactory.cs
> +                Log.Warning("There was an error registering the OpenTracing tracer.");
nit

```suggestion
              Log.Warning("An OpenTracing tracer was already registered.");
```

2022-01-17 12:18 UTC, pellared submitted a review, later dismissed

2022-01-17 22:04 UTC, pellared commented on tracer/test/Datadog.Trace.TestHelpers/IisFixture.cs
> +                var response = httpClient.GetAsync($"http://localhost:{HttpPort}{ShutdownPath}").Result;
I think it will make the build passing however the service will still return `500` if you debug it 😢

2022-01-17 22:06 UTC, dszmigielski commented on tracer/test/Datadog.Trace.TestHelpers/IisFixture.cs
> +                var response = httpClient.GetAsync($"http://localhost:{HttpPort}{ShutdownPath}").Result;
Yep, just checking if that is the root cause of tests hanging

2022-01-17 22:10 UTC, pellared commented on tracer/test/Datadog.Trace.TestHelpers/IisFixture.cs
> +                var response = httpClient.GetAsync($"http://localhost:{HttpPort}{ShutdownPath}").Result;
guess: the test is hanging b/c it waits until the service shuts down

2022-01-17 22:13 UTC, dszmigielski commented on tracer/test/Datadog.Trace.TestHelpers/IisFixture.cs
> +                var response = httpClient.GetAsync($"http://localhost:{HttpPort}{ShutdownPath}").Result;
Well, probably. The dispose method is called after the test, then the call to /home/shutdown is being made, and if it gets 500 it throws an exception that is never caught, so `_iisExpress.Process.Kill()` or `_iisExpress.Process.Dispose()` are never called.

2022-01-17 22:15 UTC, dszmigielski commented on tracer/test/Datadog.Trace.TestHelpers/IisFixture.cs
> +                var response = httpClient.GetAsync($"http://localhost:{HttpPort}{ShutdownPath}").Result;
I am not an IIS expert, so I'm not even sure what the `/home/shutdown` endpoint is supposed to do when called. Anyway it seems that adding `SignalFx.Tracing.OpenTracing.dll` breaks it.

2022-01-17 22:21 UTC, dszmigielski commented on tracer/test/Datadog.Trace.TestHelpers/IisFixture.cs
> +                var response = httpClient.GetAsync($"http://localhost:{HttpPort}{ShutdownPath}").Result;
Yep, all checks have passed now.
@pjanotti @Kielek @RassK @lachmatt @pellared does any of you have an idea why adding a dll to the tracer could break the IIS shutdown endpoint? :)

2022-01-18 08:43 UTC, Kielek commented
v 0.1.* version we have shipped OpenTracing.dll to .NET 4. 5 GAC and tracer ourput.
v 0.2.0 version does not include this library,

2022-01-18 08:59 UTC, merged