Runtime metrics docs
signalfx/signalfx-dotnet-tracing pull request #326
Opened 2022-01-18 09:14 UTC by lachmatt

## Why

Document runtime metrics configuration.

## What

Addition of `runtime-metrics.md` doc.

## Tests

n/a

2022-01-18 09:30 UTC, lachmatt commented on dev/envvars.sh
> -export SIGNALFX_METRICS_ENDPOINT_URL=${SIGNALFX_METRICS_ENDPOINT_URL:-"http://localhost:9943/v2/datapoint"}
I think these are not needed

2022-01-18 10:58 UTC, Kielek commented on tracer/src/Datadog.Trace/SignalFx/Metrics/SignalFxReporter.cs
> +                Log.Error(ex, $"Exception sending metrics: {ex.Message}");
I do not think that you need pass ex.Message. USually StackTrace includes it

2022-01-18 10:58 UTC, Kielek commented on docs/internal/runtime-metrics.md
> +| `SIGNALFX_REALM` | *ingest realm* | (__recommended__) Set to send telemetry directly to Splunk Observability Cloud. If configured, metrics are sent to `https://ingest.<SIGNALFX_REALM>.signalfx.com/
as I remeber @theletterf preferred different wording for ingest.
@theletterf, could you please check it?

2022-01-18 11:21 UTC, pellared reviewed
nit comments. I suggest to use VS Code and use `markdownlint` extension

2022-01-18 11:21 UTC, pellared commented on docs/internal/runtime-metrics.md
> +* Make sure that an `signalfx` receiver and `signalfx` exporter are configured in the collector.
is it not a description of the line above?

```suggestion
Make sure that a `signalfx` receiver and a `signalfx` exporter are configured in the collector.
```

or maybe the previous line should be removed?

2022-01-18 11:21 UTC, pellared commented on docs/internal/runtime-metrics.md
> +## Exporting directly to Splunk Observabilty Cloud
there should be a blank line after the header (applies to other places)

2022-01-18 11:21 UTC, pellared commented on docs/internal/runtime-metrics.md
> +The SignalFx Instrumentation for .NET includes an automatic runtime metrics collection.
```suggestion
The SignalFx Instrumentation for .NET is able to collect runtime metrics.
```

2022-01-18 11:21 UTC, pellared commented on docs/internal/runtime-metrics.md
> +This feature can be enabled with configuration setting and is disabled by default.
```suggestion
This feature can be enabled using configuration settings.
```

2022-01-18 11:21 UTC, pellared commented on docs/internal/runtime-metrics.md
> +When enabled, metrics are periodically captured and sent to Splunk Observability Cloud.
```suggestion
Metrics are exported on a periodic basis (push model).
```

2022-01-18 11:21 UTC, pellared commented on docs/internal/runtime-metrics.md
> +This feature can be enabled with configuration setting and is disabled by default.
Can we configure the interval?

2022-01-18 11:21 UTC, pellared commented on docs/internal/runtime-metrics.md
> +If you prefer to send metrics directly to Splunk Observability Cloud, configure the following settings:
I find it hard to process that two possibilities are described at the same time. @theletterf WDYT?

2022-01-18 11:22 UTC, pellared commented on tracer/src/Datadog.Trace/SignalFx/Metrics/SignalFxReporter.cs
> +                Log.Error(ex, $"Exception sending metrics: {ex.Message}");
It does not

2022-01-18 11:34 UTC, lachmatt commented on docs/internal/runtime-metrics.md
> +This feature can be enabled with configuration setting and is disabled by default.
its fixed

2022-01-18 11:34 UTC, lachmatt commented on docs/internal/runtime-metrics.md
> +* Make sure that an `signalfx` receiver and `signalfx` exporter are configured in the collector.
previous line removed

2022-01-18 12:09 UTC, theletterf requested changes

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +If you prefer to send metrics directly to Splunk Observability Cloud, configure the following settings:
You mean Collector + Direct ingest? We may want to clarify when direct ingest should be used first (for example, when installing a collector is not possible). How would you prefer this?

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +| `SIGNALFX_ACCESS_TOKEN` | *organization access tokens* | (__required__) See [here](https://docs.splunk.com/Observability/admin/authentication-tokens/org-tokens.html) to learn how to obtain one. |
```suggestion
| `SIGNALFX_ACCESS_TOKEN` | Your Observability Cloud token | (__required__) See [here](https://docs.splunk.com/Observability/admin/authentication-tokens/org-tokens.html) to learn how to obtain one. |
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +| `SIGNALFX_REALM` | *ingest realm* | (__recommended__) Set to send telemetry directly to Splunk Observability Cloud. If configured, metrics are sent to `https://ingest.<SIGNALFX_REALM>.signalfx.com/
```suggestion
| `SIGNALFX_REALM` | Your Observability Cloud realm | Set to send telemetry directly to Splunk Observability Cloud. If configured, metrics are sent to `https://ingest.<SIGNALFX_REALM>.signalfx.com/v2/datapoint`. To find your realm, open Splunk Observability Cloud, click Settings, then click on your username. Setting this variable also modify the default tracing endpoint. |
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +| `SIGNALFX_METRICS_ENDPOINT_URL` | *valid endpoint url* | (__optional__) Overrides other configuration settings for metrics ingestion endpoint. |
```suggestion
| `SIGNALFX_METRICS_ENDPOINT_URL` | Metric endpoint | (Optional) Overrides other settings for the metrics ingestion endpoint. |
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +__IMPORTANT:__ One of `SIGNALFX_REALM` or `SIGNALFX_METRICS_ENDPOINT_URL` has to be configured in addition to `SIGNALFX_ACCESS_TOKEN`.
```suggestion
__IMPORTANT:__ To export data directly to Splunk Observability Cloud, set `SIGNALFX_REALM` or `SIGNALFX_METRICS_ENDPOINT_URL` in addition to `SIGNALFX_ACCESS_TOKEN`.
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +### How to check if runtime metrics are enabled?
```suggestion
### Check if runtime metrics are enabled
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +The SignalFx Instrumentation for .NET logs the profiling configuration at `INF` during the startup.
```suggestion
The SignalFx Instrumentation for .NET logs the profiling configuration using `INF` log messages during startup. 
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +Verify that `runtime_metrics_enabled` key is set to `true` under `TRACER CONFIGURATION`.
```suggestion
Verify that the `runtime_metrics_enabled` key is set to `true` under `TRACER CONFIGURATION`.
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +### How to check where are metrics exported?
```suggestion
### Check where the metrics are being exported
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +Check the value of the `metrics_agent_url` key under `TRACER CONFIGURATION`.
What does it look like if the export is done locally? (Not sure if it's possible)

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +### How to verify collector setup?
```suggestion
### Verify the Collector setup
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +* Make sure you are running the [Splunk OpenTelemetry Collector](https://github.com/signalfx/splunk-otel-collector)
```suggestion
* Make sure that the [Splunk OpenTelemetry Collector](https://github.com/signalfx/splunk-otel-collector) is running.
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +* Make sure that an `signalfx` receiver and `signalfx` exporter are configured in the collector.
```suggestion
* Make sure that a `signalfx` receiver and a `signalfx` exporter are configured in the Collector.
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +Lastly, double check that the metrics pipeline is configured to use
```suggestion
* Check that the metrics pipeline is configured to use
```

2022-01-18 12:09 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +Ensure that the `access_token` and `realm` fields are [correctly configured](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter#metrics-configuratio
```suggestion
* Make sure that the `access_token` and `realm` fields are [configured](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter#metrics-configuration).
```

2022-01-18 12:09 UTC, theletterf commented on tracer/src/Datadog.Trace/SignalFx/Metrics/SignalFxReporter.cs
> +                Log.Error(ex, "An error occurred while sending metrics.");
```suggestion
                Log.Error(ex, "Metric data could not be sent.");
```

Can we make this error more informative? What does `{ex.Message}` contains? Can we add perhaps the endpoint URL in the error?

2022-01-18 12:29 UTC, lachmatt commented on docs/internal/runtime-metrics.md
> +Check the value of the `metrics_agent_url` key under `TRACER CONFIGURATION`.
it looks like this `http://localhost:9943/v2/datapoint`

2022-01-18 12:39 UTC, pellared commented on docs/internal/runtime-metrics.md
> +If you prefer to send metrics directly to Splunk Observability Cloud, configure the following settings:
I mean that it describes that direct ingest can be configured by specifying
- SIGNALFX_ACCESS_TOKEN and SIGNALFX_REALM
OR
- SIGNALFX_ACCESS_TOKEN and SIGNALFX_METRICS_ENDPOINT_URL

2022-01-18 12:42 UTC, pellared commented on docs/internal/runtime-metrics.md
> +When enabled, metrics are periodically captured and sent to Splunk Observability Cloud.
I propose the change as they can be sent to the collector.
maybe

```suggestion
When enabled, metrics are periodically captured and sent to the configured endpoint.
```

2022-01-18 13:43 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +When enabled, metrics are periodically captured and sent to Splunk Observability Cloud.
+1 Although from a customer perspective, the end goal is getting them to O11y Cloud, either via Collector or directly.

2022-01-18 13:45 UTC, theletterf approved these changes

2022-01-18 13:45 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +If you prefer to send metrics directly to Splunk Observability Cloud, configure the following settings:
```suggestion
If you prefer to send metrics to Splunk Observability Cloud without using the Collector, configure the following settings:
```

2022-01-18 13:45 UTC, theletterf commented on docs/internal/runtime-metrics.md
> +If you prefer to send metrics directly to Splunk Observability Cloud, configure the following settings:
Made an edit in the IMPORTANT note below for that.

2022-01-18 13:46 UTC, theletterf commented on tracer/src/Datadog.Trace/SignalFx/Metrics/SignalFxReporter.cs
> +                Log.Error(ex, "Metric data could not be sent.");
@pellared What did {ex.Message} contain? Can we add perhaps the endpoint URL in the error?

2022-01-18 14:02 UTC, lachmatt commented on tracer/src/Datadog.Trace/SignalFx/Metrics/SignalFxReporter.cs
> +                Log.Error(ex, "Metric data could not be sent.");
I will add the endpoint URL in separate PR

2022-01-18 14:30 UTC, lachmatt commented on docs/internal/runtime-metrics.md
> +When enabled, metrics are periodically captured and sent to Splunk Observability Cloud.
leaving it as it is for now

2022-01-18 15:17 UTC, pellared approved these changes

2022-01-19 03:37 UTC, pjanotti approved these changes

2022-01-19 06:34 UTC, merged