Fix async profiling context
signalfx/signalfx-dotnet-tracing pull request #365
Opened 2022-01-29 00:41 UTC by pjanotti

## Why

The profiling context is not being correctly handled for async/await usage.

## What

* Leveraged the `valueChangedHandler` callback to correctly update the native profiler when the async context flows between threads. Added a unit test to validate the approach, plus did some manual tests and validation. However, the approach used to simplify the tests adds a cost to the handler, we will look at optimizing it when doing the [story to benchmark span context of profiling](https://signalfuse.atlassian.net/browse/APMI-2394).

## Tests

* Manually validated that the problem was real and used the same app to validate the change
* Added unit tests to ensure that it works as expected

2022-01-31 23:15 UTC, pjanotti commented
Besides the issues with the CosmosDB emulator it seems that there is a flaky test in Kafka: https://github.com/signalfx/signalfx-dotnet-tracing/runs/5012817730?check_suite_focus=true#step:7:528

```terminal
[xUnit.net 00:03:29.53]     Datadog.Trace.ClrProfiler.IntegrationTests.KafkaTests.SubmitsTraces(packageVersion: "") [FAIL]
  Failed Datadog.Trace.ClrProfiler.IntegrationTests.KafkaTests.SubmitsTraces(packageVersion: "") [7 s]
  Error Message:
   Expected allConsumerSpans.Where(span => span.Name == $"{topic} receive") to contain 60 item(s), but found 61.

  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
   at Datadog.Trace.ClrProfiler.IntegrationTests.KafkaTests.SubmitsTraces(String packageVersion) in /project/tracer/test/Datadog.Trace.ClrProfiler.IntegrationTests/KafkaTests.cs:line 139
 ```

2022-02-01 06:32 UTC, Kielek requested changes

2022-02-01 06:32 UTC, Kielek commented on tracer/src/Datadog.Trace/AsyncLocalScopeManager.cs
>          private static readonly IDatadogLogger Log = DatadogLogging.GetLoggerFor(typeof(AsyncLocalScopeManager));
Not related to changes in this PR, but the Log is not used.

2022-02-01 06:32 UTC, Kielek commented on tracer/src/Datadog.Trace/AsyncLocalScopeManager.cs
>          private readonly AsyncLocal<Scope> _activeScope = new();
new() can be removed. The field is now initialized by the constructor.

2022-02-01 06:32 UTC, Kielek commented on tracer/src/Datadog.Trace/AsyncLocalScopeManager.cs
> +        // TODO: Move this test to a location that the native API can be accessed, add a test helper on the native side
Do you have a plan to fix it in follow up or create the jira item?

2022-02-01 06:32 UTC, Kielek commented on tracer/test/Datadog.Trace.Tests/ThreadSampling/AsyncLocalScopeManagerTests.cs
> +                Assert.Equal(scopeCtx.SpanId, profilingCtx.SpanId);
I have tried to play a bit with the test locally.
When I have added Assert.False(true); to this method, it still passes.

It fails correctly if I put such assertion out of the new Thread scope.

2022-02-01 06:35 UTC, Kielek commented on tracer/test/Datadog.Trace.Tests/ThreadSampling/AsyncLocalScopeManagerTests.cs
> +                Assert.False(tid2ProfilingCtx.ContainsKey(initialManagedThreadId));
I really like the FluentAssertion, mostly due to better messages.
consider tid2ProfilingCtx.Should().ContainKey(initialManagedThreadId); and similar for others.

What is more, you can use also https://fluentassertions.com/introduction#assertion-scopes to make sure that all issues will be listed in the test results, not only the first one.

2022-02-01 17:38 UTC, pjanotti commented on tracer/src/Datadog.Trace/AsyncLocalScopeManager.cs
> +        // TODO: Move this test to a location that the native API can be accessed, add a test helper on the native side
The plan is to use the story linked on the *What* section of the PR description - I updated the description to ensure that this is included.

2022-02-01 17:41 UTC, pjanotti commented on tracer/test/Datadog.Trace.Tests/ThreadSampling/AsyncLocalScopeManagerTests.cs
> +                Assert.Equal(scopeCtx.SpanId, profilingCtx.SpanId);
ugh, while trying to make the test reliable by adding a thread I forgot that the exception won't be captured by the test runner... the code need to flow that error outside...

2022-02-02 05:51 UTC, Kielek approved these changes

2022-02-02 05:51 UTC, merged