Linux artifacts signing
signalfx/signalfx-dotnet-tracing pull request #447
Opened 2022-03-29 15:18 UTC by pellared

## Why

Follow Splunk security guidelines.

## What

- GitLab release workflow to sign the DEB, RPM packages and checksums.txt. Signing is done using https://cd.splunkdev.com/core-ee/signing/api-integration

## Tests

Manual tests and GitLab Pipelines

## TODO (next PRs)

- Document how deb, rpm packages, and `checksums.txt` can be verified
- Start documenting the new release process

2022-03-29 15:25 UTC, pellared commented on .gitlab-ci.yml
> +    #- if: '$CI_COMMIT_TAG =~ /^v/'
IMPORTANT: this needs to be reverted

2022-03-30 10:51 UTC, RassK commented on .gitlab-ci.yml
> +    - pushd dist && shasum -a 256 * > checksums.txt && popd
Just remove dotnet.dockerfile also

2022-03-30 10:52 UTC, RassK commented on .gitlab-ci.yml
> +    - pushd dist && shasum -a 256 * > checksums.txt && popd
+ Note that for the future windows builds, we need to move artifacts to the `/repo/dist` folder.

2022-04-05 23:45 UTC, pjanotti reviewed
Nothing of much value - keep in mind that I know only the gist of python.

2022-04-05 23:45 UTC, pjanotti commented on .gitlab-ci.yml
> +    - tar -czf files.tgz $( ls dist/*.deb )
I'm clearly missing something here: where is the deb file copied to dist/?

Is the current folder tmp?

2022-04-05 23:45 UTC, pjanotti commented on scripts/signing/main.py
> +
q.: is it python style two blank lines?

2022-04-05 23:45 UTC, pjanotti commented on scripts/signing/main.py
> +        "--staging-repo", required=True, help="signing staging repository"
nit: not sure if the "signing" word adds any value to the help. It is a bit terse and it is a signing script by the description anyway.

2022-04-05 23:45 UTC, pjanotti commented on scripts/signing/main.py
> +    sign_type = SignType(args.type)
What it happens in case of typos for parser and args? Does it throw an exception?

2022-04-05 23:45 UTC, pjanotti commented on scripts/signing/main.py
> +STAGING_URL = "https://repo.splunk.com/artifactory"
Two constants that are not used in main but are defined again in sign.py.

2022-04-05 23:45 UTC, pjanotti commented on scripts/signing/sign.py
> +DEFAULT_TIMEOUT = 1200
Already defined on main.py and not used here.

2022-04-05 23:45 UTC, pjanotti commented on .gitlab-ci.yml
> +    - tar -czf files.tgz $( ls dist/*.deb )
Ah I think it is in the sign.py

2022-04-05 23:45 UTC, pjanotti commented on scripts/signing/main.py
> +
I'm seeing in other places, and given that there is no terminator for functions I'm assuming that is intentional.

2022-04-05 23:45 UTC, pjanotti commented on scripts/signing/sign.py
> +        time.sleep(10)
10 what? I don't know python 😬

2022-04-06 06:34 UTC, pellared commented on .gitlab-ci.yml
> +    - tar -czf files.tgz $( ls dist/*.deb )
- The artifacts are copied here: https://github.com/signalfx/signalfx-dotnet-tracing/blob/691e2618cd9a9f5a549302433f2b346638bfe8bd/.gitlab-ci.yml#L35
- Then they are exposed as artifacts here: https://github.com/signalfx/signalfx-dotnet-tracing/blob/691e2618cd9a9f5a549302433f2b346638bfe8bd/.gitlab-ci.yml#L36-L38
- And this makes sure that the artifacts of dependant jobs are download https://github.com/signalfx/signalfx-dotnet-tracing/blob/691e2618cd9a9f5a549302433f2b346638bfe8bd/.gitlab-ci.yml#L72-L73

2022-04-06 06:37 UTC, pellared commented on scripts/signing/main.py
> +
yes. formatted using https://github.com/psf/black and linted using https://flake8.pycqa.org/en/latest/

2022-04-06 06:37 UTC, pellared commented on scripts/signing/main.py
> +    sign_type = SignType(args.type)
correct

2022-04-06 06:38 UTC, pellared commented on scripts/signing/sign.py
> +        time.sleep(10)
seconds 😄

2022-04-06 06:44 UTC, pellared commented
@pjanotti Thanks for the review. Now, I have spotted that I have forgotten to remove all the Python scripts 🤦 As of right now everything comes thanks to

```yaml
include:
  # repo: https://cd.splunkdev.com/core-ee/signing/api-integration/-/tree/develop/
  - project: core-ee/signing/api-integration
    ref: develop
    file: /templates/.sign-client.yml
```

which is reusued in the `sign-deb` , `sign-rpm`, `checksums` jobs

2022-04-06 08:08 UTC, pellared commented on .gitlab-ci.yml
> -    - if: '$CI_COMMIT_TAG =~ /^v/'
This is not needed as the builds are not triggered when syncing with GitHub

The workflow is executed only if one pushes directly to GitLab or uses the GitLab UI to run a workflow

2022-04-25 00:24 UTC, pjanotti requested changes
Last that I checked it LGTM, but, let's block merges until pull from upstream is done.

2022-05-24 17:02 UTC, pjanotti approved these changes
LGTM

2022-05-25 04:30 UTC, Kielek approved these changes

2022-05-25 05:07 UTC, merged