[WIP] Upstream pull followup - Reuse upstream propagation code
signalfx/signalfx-dotnet-tracing pull request #465
Opened 2022-04-20 14:20 UTC by dszmigielski

## Why

We don't need our propagation code anymore as it is now available in the upstream repo.

## What

Reuse upstream propagation code which was recently refactored here:  [SpanContextPropagator refactor by tonyredondo · Pull Request #2536 · DataDog/dd-trace-dotnet](https://github.com/DataDog/dd-trace-dotnet/pull/2536)

## Tests

2022-04-20 14:43 UTC, RassK commented on tracer/src/Datadog.Trace/Configuration/ConfigurationKeys.cs
> +        public const string PropagationStyleInject = "SINGALFX_PROPAGATION_STYLE_INJECT";
this is a breaking change. not sure if we should actually do it.
Might be better to leave the original `SIGNALFX_PROPAGATORS`, document these 2 new vars in internal config and assign value from `SIGNALFX_PROPAGATORS`

2022-04-20 15:05 UTC, dszmigielski commented on tracer/src/Datadog.Trace/Configuration/ConfigurationKeys.cs
> +        public const string PropagationStyleInject = "SINGALFX_PROPAGATION_STYLE_INJECT";
Good point, I will preserve our variable name and populate new properties from its value.

2022-04-25 00:25 UTC, pjanotti requested changes
I didn't look at it yet, but, let's block merges until pull from upstream is done.

2022-04-28 09:53 UTC, Kielek commented
Do you see any option to remove everything under `Datadog.Trace.Propagation` namespace? It is not available on the upstream side.

2022-04-28 10:00 UTC, dszmigielski commented
> Do you see any option to remove everything under `Datadog.Trace.Propagation` namespace? It is not available on the upstream side.

What is left there are header names and some extensions that we are still using. I would rather leave them be tbh.

2022-04-28 11:45 UTC, RassK approved these changes

2022-04-28 11:54 UTC, Kielek commented on tracer/src/Datadog.Trace/Configuration/TracerSettings.cs
> +            PropagationStyleInject = TrimSplitString(source?.GetString(ConfigurationKeys.Propagators) ?? nameof(Propagators.ContextPropagators.Names.B3), ',').ToArray();
You have the same logic twice. Consider to call it only once.

2022-04-28 11:57 UTC, Kielek reviewed
One more thing, did you have chance to verify if long TraceId is correctly propagated? As I remember upstream supports only short TraceIds.

2022-04-28 11:57 UTC, Kielek commented on tracer/test/snapshots/GrpcLegacy.SubmitTraces_httpclient=Disabled.verified.txt
> +    Name: SendBothStreamingRequest,
I am not able to verify this file. Please check if the changes are expected.

2022-04-29 07:44 UTC, merged