Bump .NET versions
signalfx/signalfx-dotnet-tracing pull request #531
Opened 2022-06-15 06:45 UTC by Kielek

## Why

To mitigate https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-30184

## What
Bump .NET versions
3.1.416 => 3.1.420
5.0.405 => 5.0.408
6.0.200 => 6.0.301

## Tests

CI

2022-06-15 09:33 UTC, pellared approved these changes

2022-06-15 09:56 UTC, lachmatt approved these changes

2022-06-15 10:16 UTC, pellared requested changes
I think we should also update

- `alpine.dockerfile`
- `debian.dockerfile`

In `tracer/build/_build/docker` directory

2022-06-15 15:13 UTC, RassK commented on profiler/src/ProfilerEngine/Datadog.Profiler.Native/Datadog.Profiler.Native.vcxproj
> +    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
Any good reason losing patch version here?

2022-06-15 15:35 UTC, Kielek commented on profiler/src/ProfilerEngine/Datadog.Profiler.Native/Datadog.Profiler.Native.vcxproj
> +    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
This version is not available on Windows 2022. What is more, for now, we are not using this library,

2022-06-15 15:50 UTC, pellared commented on profiler/src/ProfilerEngine/Datadog.Profiler.Native/Datadog.Profiler.Native.vcxproj
> +    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
Can we use a version which is available? Or remove this line?

2022-06-15 15:59 UTC, Kielek commented on profiler/src/ProfilerEngine/Datadog.Profiler.Native/Datadog.Profiler.Native.vcxproj
> +    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
10.0 is used in all other files. Only DD-profiler has different configuration. See https://github.com/signalfx/signalfx-dotnet-tracing/blob/5417e4dd6a8a8e37aeaef638242e4217b81f345c/tracer/src/Datadog.Trace.ClrProfiler.Native/Datadog.Trace.ClrProfiler.Native.DLL.vcxproj#L25

2022-06-15 15:59 UTC, Kielek commented
> I think we should also update
> 
> * `alpine.dockerfile`
> * `debian.dockerfile`
> 
> In `tracer/build/_build/docker` directory

Fixed.

2022-06-15 17:38 UTC, pellared commented on profiler/src/ProfilerEngine/Datadog.Profiler.Native/Datadog.Profiler.Native.vcxproj
> +    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
AFAIK we should try to pin the version if possible. We can deal with it in a separate PR.

2022-06-15 17:38 UTC, pellared approved these changes

2022-06-15 18:36 UTC, pjanotti approved these changes

2022-06-15 19:27 UTC, Kielek commented on .github/workflows/ci.yml
> +    - name: install Microsoft.Net.Component.4.6.1.TargetingPack
You are right.

2022-06-16 09:52 UTC, RassK approved these changes

2022-06-17 08:34 UTC, Kielek commented on profiler/src/ProfilerEngine/Datadog.Profiler.Native/Datadog.Profiler.Native.vcxproj
> +    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
Separate task created.

2022-06-17 08:45 UTC, merged