[AlwaysOnProfiler] Internal docs
signalfx/signalfx-dotnet-tracing pull request #641
Opened 2022-10-13 09:08 UTC by lachmatt

## Why

Document Memory Profiler.

## What

- Separate file in internal docs for MemoryProfiler.
- Update `always-on-profiling.md` after recent logging changes.
- Add troubleshooting logs.

## Tests

n/a

2022-10-13 09:11 UTC, dszmigielski reviewed
I think @theletterf should have a look :)

2022-10-13 09:18 UTC, dszmigielski commented on docs/internal/memory-profiling.md
> +For every sampled allocation, allocation amount together with state of the thread
```suggestion
For every sampled allocation, allocation amount as well as the state of the thread
```

2022-10-13 09:26 UTC, Kielek approved these changes
LGTM. Some minor comments for consideration.

2022-10-13 09:26 UTC, Kielek commented on docs/internal/memory-profiling.md
> +> _NOTE_: `SIGNALFX_PROFILER_LOGS_ENDPOINT` affects both CPU and Memory profiling.
Do we need same note for always-on-profiler?

2022-10-13 09:26 UTC, Kielek commented on docs/internal/memory-profiling.md
> +* .NET 5.0 or higher (`ICorProfilerInfo12` available in runtime).
The question is if we should reference in memory profiling .NET 5 or 6. 
.NET 5 is EOL.

2022-10-13 12:42 UTC, theletterf requested changes
FYI, this is the final shape of the Java version: https://docs.splunk.com/Observability/gdi/get-data-in/application/java/troubleshooting/common-java-troubleshooting.html#troubleshoot-alwayson-profiling-for-java

2022-10-13 12:42 UTC, theletterf commented on docs/always-on-profiling.md
>  At the startup, the SignalFx Instrumentation for .NET will log the string
```suggestion
At the startup, the SignalFx Instrumentation for .NET logs the string
```

2022-10-13 12:42 UTC, theletterf commented on docs/always-on-profiling.md
> +`AlwaysOnProfiler::StartThreadSampling` at `info` log level
```suggestion
`AlwaysOnProfiler::StartThreadSampling` at `info` log level.
```

2022-10-13 12:42 UTC, theletterf commented on docs/always-on-profiling.md
> +results in the following entry in the managed logs for the instrumentation:
```suggestion
If you try to enable CPU Profiler on the unsupported runtime version, you'll get
a log entry similar to the following in the managed logs for the instrumentation:
```

2022-10-13 12:42 UTC, theletterf commented on docs/always-on-profiling.md
>  ## How can I see the profiler configuration?
```suggestion
## How can I see AlwaysOn Profiling configuration?
```

Clarified, as I understand "profiler" has a native and distinct meaning in .NET

2022-10-13 12:42 UTC, theletterf commented on docs/always-on-profiling.md
>  If the escape hatch activates, it logs the following message:
What's the criteria for the escape hatch to activate?

2022-10-13 12:42 UTC, theletterf commented on docs/always-on-profiling.md
> +** THIS WILL RESULT IN LOSS OF PROFILING DATA **.
Any chance we could edit this error message before it hits prod? CAPS ARE A BIT DRAMATIC! 😅

2022-10-13 12:42 UTC, theletterf commented on docs/internal/memory-profiling.md
> +can then be used to investigate memory leaks and unusual consumption patterns.
```suggestion
The SignalFx Instrumentation for .NET includes a memory profiler for Splunk
APM that can be enabled with a setting. The profiler samples allocations,
captures the call stack state for the .NET thread that triggered the allocation,
and sends the telemetry to Splunk Observability Cloud.

Use the memory allocation data, together with the stack traces and .NET runtime metrics,
to investigate memory leaks and unusual consumption patterns in AlwaysOn Profiling.
```

The fact that we send this data as logs, AFAIK, is just an implementation detail. It's not relevant to users.

2022-10-13 12:42 UTC, theletterf commented on docs/internal/memory-profiling.md
> +# About the .NET Memory Profiling
```suggestion
# About the AlwaysOn memory profiling for .NET
```

2022-10-13 12:42 UTC, theletterf commented on docs/internal/memory-profiling.md
> +processes the data from the buffer and sends it to the OpenTelemetry Collector.
```suggestion
The managed thread shared with [CPU Profiler](../always-on-profiling.md)
processes the data from the buffer and sends it to the OpenTelemetry Collector.
```

2022-10-13 12:42 UTC, theletterf commented on docs/internal/memory-profiling.md
> +Please check the descriptions for the following environment variable:
```suggestion
Make sure you're following the documentation for the following environment variables:
```

2022-10-13 13:16 UTC, lachmatt commented on docs/always-on-profiling.md
>  If the escape hatch activates, it logs the following message:
It's described above: https://github.com/signalfx/signalfx-dotnet-tracing/blob/307fcefd7336c768dc1c4251559beef4d6f93af4/docs/always-on-profiling.md#escape-hatch

2022-10-13 13:25 UTC, lachmatt commented on docs/internal/memory-profiling.md
> +> _NOTE_: `SIGNALFX_PROFILER_LOGS_ENDPOINT` affects both CPU and Memory profiling.
added in https://github.com/signalfx/signalfx-dotnet-tracing/pull/641/commits/6b90d6bcbacf338bb3bfe01d45f532a6a5c1fc75

2022-10-13 18:16 UTC, pjanotti approved these changes
LGTM, minor suggestions.

2022-10-13 18:16 UTC, pjanotti commented on docs/internal/memory-profiling.md
> +to investigate memory leaks and unusual consumption patterns in AlwaysOn Profiling.
To me this reads like one is investigating memory leaks and consumption in "AlwaysOn Profiling". I will defer to @theletterf judgement here.

2022-10-13 18:16 UTC, pjanotti commented on docs/internal/memory-profiling.md
> +For every sampled allocation, allocation amount as well as the state of the thread
The state of the thread is always the same, no? I mean it is a running thread. I understand that this is part of the export format info but seems redundant here.

2022-10-13 18:18 UTC, pjanotti commented on docs/internal/memory-profiling.md
> +* .NET 5.0 or higher (`ICorProfilerInfo12` available in runtime).
Since our current requirements say .NET 5.0 (see https://github.com/signalfx/signalfx-dotnet-tracing#requirements) I vote for .NET 5.0

2022-10-14 06:00 UTC, lachmatt commented on docs/internal/memory-profiling.md
> +to investigate memory leaks and unusual consumption patterns in AlwaysOn Profiling.
Current wording was suggested in https://github.com/signalfx/signalfx-dotnet-tracing/pull/641/commits/a6d5fe2c59773f56740829510eab4423b7b0dcb0

2022-10-14 06:13 UTC, lachmatt commented on docs/internal/memory-profiling.md
> +used to store allocation samples is full.
added limit information in https://github.com/signalfx/signalfx-dotnet-tracing/pull/641/commits/62ed5a18c668cea5418b3c08b41aa0547c0f0bfb

2022-10-14 06:13 UTC, lachmatt commented on docs/internal/memory-profiling.md
> +For every sampled allocation, allocation amount as well as the state of the thread
reworded to avoid confusion in https://github.com/signalfx/signalfx-dotnet-tracing/pull/641/commits/62ed5a18c668cea5418b3c08b41aa0547c0f0bfb

2022-10-14 06:14 UTC, lachmatt commented on docs/always-on-profiling.md
> +** THIS WILL RESULT IN LOSS OF PROFILING DATA **.
Will be adjusted with a separate PR.

2022-10-14 06:17 UTC, Kielek approved these changes

2022-10-14 07:30 UTC, merged