[Runtime Metrics] Time in gc metric
signalfx/signalfx-dotnet-tracing pull request #643
Opened 2022-10-17 08:56 UTC by lachmatt

## Why

Reintroduce metric that shows time spent in gc pause.

## What

- reintroduce implementation from upstream (.NET Core only)
- send as a double-valued counter

## Tests

Included in PR.

2022-10-17 09:04 UTC, Kielek approved these changes

2022-10-17 09:14 UTC, theletterf requested changes

2022-10-17 09:14 UTC, theletterf commented on docs/metrics.md
> +| `process.runtime.dotnet.thread_pool.threads.count`     | The number of thread pool threads, as observed during the latest measurement. (.NET Core only)                                  | Gauge
```suggestion
|:-------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------|:------------------|
| `process.runtime.dotnet.exceptions.count`              | Count of exceptions since the previous observation.                                   | Counter           |
| `process.runtime.dotnet.gc.collections.count`          | Number of garbage collections since the process started.                                             | CumulativeCounter |
| `process.runtime.dotnet.gc.heap.size`                  | Heap size, as observed during the last garbage collection.                                                                | Gauge             |
| `process.runtime.dotnet.gc.allocations.size`           | Count of bytes allocated on the managed GC heap since the process started. (.NET Core only)                             | CumulativeCounter |
| `process.runtime.dotnet.gc.committed_memory.size`      | Amount of committed virtual memory for the managed GC heap, as observed during the last garbage collection. (.NET 6 only) | Gauge             |
| `process.runtime.dotnet.gc.pause.time`                 | Number of milliseconds spent in GC pause. (.NET Core only)                                                                  | Counter           |
| `process.runtime.dotnet.monitor.lock_contention.count` | Contentions count when trying to acquire a monitor lock since the process started.                   | CumulativeCounter |
| `process.runtime.dotnet.thread_pool.threads.count`     | Number of thread pool threads, as observed during the last measurement. Only available for .NET Core.                                  | Gauge             |
```

2022-10-17 09:22 UTC, theletterf approved these changes

2022-10-17 17:23 UTC, pjanotti commented on tracer/src/Datadog.Trace/RuntimeMetrics/RuntimeEventListener.cs
> +                var start = _gcStart;
It seems safer to set `_gcStart` to null after saving the current value to the local. At least with ETW it was possible to miss some events - I'm not sure if that is the case for EventPipe but the cost is very low to avoid bogus data.

2022-10-17 17:23 UTC, pjanotti commented on tracer/src/Datadog.Trace/RuntimeMetrics/RuntimeEventListener.cs
> +        private const int EventGcSuspendBegin = 9;
This got me on the wrong track: the MS doc seems to be wrong putting the event ID as 8, see https://learn.microsoft.com/en-us/dotnet/fundamentals/diagnostics/runtime-garbage-collection-events#gcsuspendeebegin_v1-event

At least I think this is the intended event. That said I'm now questioning if start with id 9 shouldn't be matched with end id 8 instead. I assume this is based on the OTel SDK, could you please link the corresponding code/PR?

2022-10-17 17:23 UTC, pjanotti commented on tracer/src/Datadog.Trace/RuntimeMetrics/RuntimeEventListener.cs
> +            else if (eventData.EventId == EventGcSuspendBegin)
It would be nice to have link here or on the enum to some doc describing these events.

2022-10-17 17:23 UTC, pjanotti commented on tracer/src/Datadog.Trace/RuntimeMetrics/RuntimeEventListener.cs
> +                    _statsd.IncrementDouble(MetricsNames.Gc.PauseTime, (eventData.TimeStamp - start.Value).TotalMilliseconds);
What are the dimensions/tags that are attached to this metric?

2022-10-18 10:47 UTC, lachmatt commented on tracer/src/Datadog.Trace/RuntimeMetrics/RuntimeEventListener.cs
> +                var start = _gcStart;
fixed in https://github.com/signalfx/signalfx-dotnet-tracing/pull/643/commits/8386277b2b543869362f412e61a30a706f00c912

2022-10-18 10:47 UTC, lachmatt commented on tracer/src/Datadog.Trace/RuntimeMetrics/RuntimeEventListener.cs
> +            else if (eventData.EventId == EventGcSuspendBegin)
fixed in https://github.com/signalfx/signalfx-dotnet-tracing/pull/643/commits/8386277b2b543869362f412e61a30a706f00c912

2022-10-18 10:49 UTC, lachmatt commented on tracer/src/Datadog.Trace/RuntimeMetrics/RuntimeEventListener.cs
> +                    _statsd.IncrementDouble(MetricsNames.Gc.PauseTime, (eventData.TimeStamp - start.Value).TotalMilliseconds);
default tags from https://github.com/signalfx/signalfx-dotnet-tracing/blob/ba64bece9ad776f361abe593e5f3d449cdeaadd5/tracer/src/Datadog.Trace/TracerManagerFactory.cs#L199

2022-10-18 18:30 UTC, pjanotti approved these changes

2022-10-18 18:30 UTC, merged