WIP: Add servertiming header
signalfx/signalfx-dotnet-tracing pull request #96
Opened 2021-04-09 12:27 UTC by dszmigielski

Intorducing severtiming header. This required porting of 128bit TraceId, propagation changes and W3C propagator from otel repo.

@signalfx/instrumentation

2021-04-12 13:20 UTC, johnbley requested changes

2021-04-12 13:20 UTC, johnbley commented on src/Datadog.Trace/Configuration/ConfigurationKeys.cs
> +        public const string SplunkContextServerTimingEnabled = "SIGNALFX_SPLUNK_CONTEXT_SERVER_TIMING_ENABLED";
I don't think this is the right property name to align with the others.  We've used `SIGNALFX_` and `SPLUNK_` but not both at once :-)

2021-04-12 13:20 UTC, johnbley commented on src/Datadog.Trace/ServerTimingHeader.cs
> +            var traceContextHeaders = new Dictionary<string, string>();
Might as well initialize with an "expected" size - `new Dictionary<string, string>(1);`?

2021-04-12 13:20 UTC, johnbley commented on src/Datadog.Trace/ServerTimingHeader.cs
> +        private const string ServerTimingFormat = "traceparent;desc=\"{0}\"";
I don't see a test that validates the actual Server-Timing header, only some for the traceparent formatting?  Or am I missing it?

2021-04-12 19:31 UTC, pellared commented on src/Datadog.Trace/Configuration/ConfigurationKeys.cs
> +        public const string SplunkContextServerTimingEnabled = "SIGNALFX_SPLUNK_CONTEXT_SERVER_TIMING_ENABLED";
I think it should be `SIGNALFX_TRACE_RESPONSE_HEADER_ENABLED`
Reference: https://github.com/signalfx/gdi-specification/blob/main/docs/configuration.md#instrumentation-libraries

2021-04-12 19:33 UTC, pellared commented on src/Datadog.Trace/Configuration/TracerSettings.cs
> +                                               false;
default value should be `true`.
See: https://github.com/signalfx/gdi-specification/blob/main/docs/configuration.md#instrumentation-libraries

2021-04-12 19:36 UTC, pellared commented on src/Datadog.Trace/Configuration/TracerSettings.cs
> +        public bool SplunkContextServerTimingEnabled { get; set; }
Same comment as https://github.com/signalfx/signalfx-dotnet-tracing/pull/96/files#r611898826

2021-04-12 19:40 UTC, pellared commented on src/Datadog.Trace/Datadog.Trace.csproj
> +    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2" />
what will happen if the instrumented code would reference e.g. [5.0.0](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/5.0.0) or some version that will be incompatbile?

2021-04-14 08:46 UTC, dszmigielski commented on src/Datadog.Trace/Datadog.Trace.csproj
> +    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2" />
Tbh I don't know, we have exactly the same thing in otel repo :o

2021-04-14 11:03 UTC, pellared commented on src/Datadog.Trace/Datadog.Trace.csproj
> +    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2" />
I guess it will lead to a runtime exception. We have a SIG meeting today so you can ask. Can you create a GH issue for it in OTel, please?

2021-04-14 19:38 UTC, pellared commented on src/Datadog.Trace/Datadog.Trace.csproj
> +    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2" />
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/127

2021-04-15 17:36 UTC, pellared commented on src/Datadog.Trace/Datadog.Trace.csproj
> +    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2" />
IMO from the perspective of this repo it is critical to fix it as lots of customers are already using it.
We do not want issues like this: https://github.com/DataDog/dd-trace-dotnet/issues/771

OTel is in an early pre-release state. Therefore for OTel repo issues like this are severe, but not a blocker.

2021-04-16 13:47 UTC, pellared commented on src/Datadog.Trace/ServerTimingHeader.cs
> +        public const string ServerTimingHeaderName = "Server-Timing";
nit: we have no tests to ensure that these values are OK 😉 
https://leanpub.com/tdd-ebook/read#leanpub-auto-fourth-technique-constant-specification

This is one of the reasons I am often not using constants from production code in tests. 
Sometimes I copy-paste the same constants to test code.
It is good to have a safety net for such constants if they are important - this one is.
See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/119 for an example

2021-04-16 13:54 UTC, pellared commented on src/Datadog.Trace/ServerTimingHeader.cs
> +                setter(carrier, ExposeHeadersHeaderName, ExposeHeadersHeaderValue);
personally, I would prefer to simply use `ServerTimingHeaderName` instead and get rid of `ExposeHeadersHeaderValue`. too many layers of indirection. Also from perspective of this code we want to make sure that `ServerTimingHeaderName` us set here b/c of previous line

2021-04-16 13:59 UTC, pellared commented on test/Datadog.Trace.Tests/ServerTimingHeaderTests.cs
> +
can you add something to `Server-Timing` and `Access-Control-Expose-Headers` headers before invoking `ServerTimingHeader.SetHeaders` and then make sure that new values are appended (but they are not replacing previous values)?

2021-04-16 14:04 UTC, pellared commented on test/Datadog.Trace.Tests/ServerTimingHeaderTests.cs
> +                headers.GetValues(ServerTimingHeader.ServerTimingHeaderName).First().Should().Be($"traceparent;desc=\"00-{traceId.ToString()}-000000000000007b-01\"");
I am sure this could be done in line.
try:
```
headers.GetValues(ServerTimingHeader.ServerTimingHeaderName).First().Should().Equal($"traceparent;desc=\"00-{traceId.ToString()}-000000000000007b-01\"");
```

2021-04-16 14:05 UTC, pellared commented on src/Datadog.Trace/ServerTimingHeader.cs
> +            W3CSpanContextPropagator.Instance.Inject(context, traceContextHeaders, (dictionary, headerName, headerValue) => dictionary[headerName] = headerValue);
is the behaviour of this one line tested? looks like an important side-effect

2021-04-16 14:07 UTC, pellared commented on test/Datadog.Trace.Tests/W3CSpanContextPropagatorTests.cs
> +                headers.GetValues(W3CHeaderNames.TraceParent).Should().BeEquivalentTo(new List<string> { "00-0af7651916cd43dd8448eb211c80319c-00f067aa0ba902b7-01" });
try:
```
headers.GetValues(W3CHeaderNames.TraceParent).Should().Equal("00-0af7651916cd43dd8448eb211c80319c-00f067aa0ba902b7-01");

2021-04-16 14:09 UTC, pellared commented on test/Datadog.Trace.Tests/W3CSpanContextPropagatorTests.cs
> +                headers.GetValues(W3CHeaderNames.TraceParent).Should().BeEquivalentTo(new List<string> { "00-0af7651916cd43dd8448eb211c80319c-00f067aa0ba902b7-01" });
AssertionScope would be usless

2021-04-16 14:10 UTC, pellared commented on test/Datadog.Trace.Tests/Datadog.Trace.Tests.csproj
> +    <PackageReference Include="FluentAssertions" Version="5.10.3" />
❤️

2021-04-19 07:55 UTC, dszmigielski commented on src/Datadog.Trace/ServerTimingHeader.cs
> +            W3CSpanContextPropagator.Instance.Inject(context, traceContextHeaders, (dictionary, headerName, headerValue) => dictionary[headerName] = headerValue);
Do you mean injecting the header using the W3C propagator? It is tested in unit test, that the injected value is correct.

2021-04-19 12:57 UTC, johnbley approved these changes

2021-04-28 17:04 UTC, pjanotti commented
@dszmigielski @johnbley the tests are failing because the server timing headers are missing for some "bad request" responses. I assume that we want the headers even on such cases, correct?

2021-04-28 17:11 UTC, pjanotti reviewed
If headers should be added to bad request responses the code need to cover the exception cases.

2021-04-28 17:11 UTC, pjanotti commented on test/Datadog.Trace.ClrProfiler.IntegrationTests/AspNetCore/AspNetCoreMvcTestBase.cs
> +                        $"No Server-Timing header attached. Headers present: {string.Join(", ", response.Headers)}");
I recommend adding the path to this message and the one below to identify which path failed. Same for the assert below. Also, `response.Headers` default ToString is not very informative.

2021-04-28 17:11 UTC, pjanotti commented on test/Datadog.Trace.ClrProfiler.IntegrationTests/Helpers/TestHelper.cs
> +                    $"No Server-Timing header attached. Headers present: {string.Join(", ", response.Headers)}");
Same comment as similar code above.

2021-04-28 17:14 UTC, johnbley commented on test/Datadog.Trace.ClrProfiler.IntegrationTests/Helpers/TestHelper.cs
> +                    $"No Server-Timing header attached. Headers present: {string.Join(", ", response.Headers)}");
Yes, we'd ideally like the header for every request that generated a server span, but if that's going to involve a redesign then I'd say commit this progress now and revisit later.

2021-04-29 10:28 UTC, pellared approved these changes

2021-04-29 10:29 UTC, pellared commented on .gitignore
> +.DS_Store
@dszmigielski 
I encourage you to take a look at https://gist.github.com/subfuzion/db7f57fff2fb6998a16c 😉

2021-04-29 19:32 UTC, pjanotti approved these changes
LGTM

2021-04-29 22:24 UTC, pjanotti commented
Flaky tests:

Same flaky test:

```
2021-04-29T21:49:09.7421340Z [xUnit.net 00:00:11.2138365]     Datadog.Trace.Tests.Sampling.RateLimiterTests.Limits_Approximately_To_Defaults [FAIL]
2021-04-29T21:49:09.7528908Z   X Datadog.Trace.Tests.Sampling.RateLimiterTests.Limits_Approximately_To_Defaults [8s 426ms]
2021-04-29T21:49:09.7530650Z   Error Message:
2021-04-29T21:49:09.7531725Z    Expected between 714 and 915, received 701 out of 4000 within 8140.0557 milliseconds.
2021-04-29T21:49:09.7532716Z Expected: True
2021-04-29T21:49:09.7533410Z Actual:   False
2021-04-29T21:49:09.7534159Z   Stack Trace:
2021-04-29T21:49:09.7537570Z      at Datadog.Trace.Tests.Sampling.RateLimiterTests.Run_Limit_Test(Nullable`1 intervalLimit, Int32 numberPerBurst, Int32 numberOfBursts, Int32 millisecondsBetweenBursts) in D:\a\1\s\test\Datadog.Trace.Tests\Sampling\RateLimiterTests.cs:line 86
2021-04-29T21:49:09.7539863Z    at Datadog.Trace.Tests.Sampling.RateLimiterTests.Limits_Approximately_To_Defaults() in D:\a\1\s\test\Datadog.Trace.Tests\Sampling\RateLimiterTests.cs:line 56
2021-04-29T21:49:15.2517370Z Results File: D:\a\_temp\VssAdministrator_WIN-16SS5M8JT0C_2021-04-29_21_49_00.trx
2021-04-29T21:49:15.2518686Z 
2021-04-29T21:49:15.2535472Z Test Run Failed.
2021-04-29T21:49:15.2536534Z Total tests: 312
2021-04-29T21:49:15.2537779Z      Passed: 311
2021-04-29T21:49:15.2538716Z      Failed: 1
2021-04-29T21:49:15.2540200Z  Total time: 17.4239 Seconds

2021-04-29T21:49:28.9279954Z   X Datadog.Trace.Tests.Sampling.RateLimiterTests.Limits_Approximately_To_Defaults [8s 314ms]
2021-04-29T21:49:28.9282488Z   Error Message:
2021-04-29T21:49:28.9283538Z    Expected between 704 and 905, received 602 out of 4001 within 8041.0129 milliseconds.
2021-04-29T21:49:28.9284274Z Expected: True
2021-04-29T21:49:28.9284629Z Actual:   False
2021-04-29T21:49:28.9285108Z   Stack Trace:
2021-04-29T21:49:28.9286169Z      at Datadog.Trace.Tests.Sampling.RateLimiterTests.Run_Limit_Test(Nullable`1 intervalLimit, Int32 numberPerBurst, Int32 numberOfBursts, Int32 millisecondsBetweenBursts) in D:\a\1\s\test\Datadog.Trace.Tests\Sampling\RateLimiterTests.cs:line 86
2021-04-29T21:49:28.9287466Z    at Datadog.Trace.Tests.Sampling.RateLimiterTests.Limits_Approximately_To_Defaults() in D:\a\1\s\test\Datadog.Trace.Tests\Sampling\RateLimiterTests.cs:line 56
2021-04-29T21:49:33.9421362Z Results File: D:\a\_temp\VssAdministrator_WIN-16SS5M8JT0C_2021-04-29_21_49_18.trx
2021-04-29T21:49:33.9422642Z 
2021-04-29T21:49:33.9440349Z Test Run Failed.
2021-04-29T21:49:33.9441636Z Total tests: 316
2021-04-29T21:49:33.9442548Z      Passed: 314
2021-04-29T21:49:33.9443474Z      Failed: 2
2021-04-29T21:49:33.9445210Z  Total time: 18.1409 Seconds
```

Some race condition here:
```
2021-04-29T21:49:23.8678895Z [xUnit.net 00:00:07.3318227]     Datadog.Trace.Tests.AgentWriterTests.WriteTrace_2Traces_SendToApi(synchronousSend: False) [FAIL]
2021-04-29T21:49:24.4205265Z   X Datadog.Trace.Tests.AgentWriterTests.WriteTrace_2Traces_SendToApi(synchronousSend: False) [5s 135ms]
2021-04-29T21:49:24.4207126Z   Error Message:
2021-04-29T21:49:24.4207994Z    Moq.MockException : 
2021-04-29T21:49:24.4209069Z Expected invocation on the mock once, but was 0 times: x => x.SendTracesAsync(It.Is<Span[][]>(y => y.Single<Span[]>().Equals([TraceId: 
2021-04-29T21:49:24.4210563Z ParentId: 0
2021-04-29T21:49:24.4211617Z SpanId: 2531867559493136555
2021-04-29T21:49:24.4212420Z ServiceName: 
2021-04-29T21:49:24.4213213Z OperationName: 
2021-04-29T21:49:24.4213954Z Resource: 
2021-04-29T21:49:24.4216770Z Type: 
2021-04-29T21:49:24.4217579Z Start: 1/1/0001 12:00:00 AM +00:00
2021-04-29T21:49:24.4218428Z Duration: 00:00:00
2021-04-29T21:49:24.4219125Z Error: False
2021-04-29T21:49:24.4219812Z Meta:
2021-04-29T21:49:24.4220448Z Logs:
2021-04-29T21:49:24.4221042Z Metrics:
2021-04-29T21:49:24.4221686Z ])))
2021-04-29T21:49:24.4222366Z No setups configured.
2021-04-29T21:49:24.4223151Z No invocations performed.
2021-04-29T21:49:24.4223844Z   Stack Trace:
2021-04-29T21:49:24.4225655Z      at Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount)
2021-04-29T21:49:24.4227652Z    at Moq.Mock.VerifyCalls(Mock targetMock, MethodCall expected, Expression expression, Times times)
2021-04-29T21:49:24.4228933Z    at Moq.Mock.Verify[T,TResult](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
2021-04-29T21:49:24.4230024Z    at Moq.Mock`1.Verify[TResult](Expression`1 expression, Func`1 times)
2021-04-29T21:49:24.4231343Z    at Datadog.Trace.Tests.AgentWriterTests.<WriteTrace_2Traces_SendToApi>d__0.MoveNext() in D:\a\1\s\test\Datadog.Trace.Tests\AgentWriterTests.cs:line 37
2021-04-29T21:49:24.4233155Z --- End of stack trace from previous location where exception was thrown ---
2021-04-29T21:49:24.4234069Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-04-29T21:49:24.4235166Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-04-29T21:49:24.4236268Z --- End of stack trace from previous location where exception was thrown ---
2021-04-29T21:49:24.4238321Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-04-29T21:49:24.4239443Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-04-29T21:49:24.4240390Z --- End of stack trace from previous location where exception was thrown ---
2021-04-29T21:49:24.4241258Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2021-04-29T21:49:24.4242262Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-04-29T21:49:28.4210804Z [xUnit.net 00:00:11.9079931]     Datadog.Trace.Tests.Sampling.RateLimiterTests.Limits_Approximately_To_Defaults [FAIL]
2021-04-29T21:49:28.9279954Z   X Datadog.Trace.Tests.Sampling.RateLimiterTests.Limits_Approximately_To_Defaults [8s 314ms]
2021-04-29T21:49:28.9282488Z   Error Message:
2021-04-29T21:49:28.9283538Z    Expected between 704 and 905, received 602 out of 4001 within 8041.0129 milliseconds.
2021-04-29T21:49:28.9284274Z Expected: True
2021-04-29T21:49:28.9284629Z Actual:   False
2021-04-29T21:49:28.9285108Z   Stack Trace:
2021-04-29T21:49:28.9286169Z      at Datadog.Trace.Tests.Sampling.RateLimiterTests.Run_Limit_Test(Nullable`1 intervalLimit, Int32 numberPerBurst, Int32 numberOfBursts, Int32 millisecondsBetweenBursts) in D:\a\1\s\test\Datadog.Trace.Tests\Sampling\RateLimiterTests.cs:line 86
2021-04-29T21:49:28.9287466Z    at Datadog.Trace.Tests.Sampling.RateLimiterTests.Limits_Approximately_To_Defaults() in D:\a\1\s\test\Datadog.Trace.Tests\Sampling\RateLimiterTests.cs:line 56
2021-04-29T21:49:33.9421362Z Results File: D:\a\_temp\VssAdministrator_WIN-16SS5M8JT0C_2021-04-29_21_49_18.trx
2021-04-29T21:49:33.9422642Z 
2021-04-29T21:49:33.9440349Z Test Run Failed.
2021-04-29T21:49:33.9441636Z Total tests: 316
2021-04-29T21:49:33.9442548Z      Passed: 314
2021-04-29T21:49:33.9443474Z      Failed: 2
2021-04-29T21:49:33.9445210Z  Total time: 18.1409 Seconds
```

2021-05-03 14:28 UTC, iNikem commented
@pellared @johnbley @pjanotti Anything else is needed here or can we merge this PR?

2021-05-03 20:51 UTC, johnbley commented
We're good here I think

2021-05-04 16:51 UTC, merged